### ISSUE TITLE
[Drawer] Height issue

### ISSUE THREAD

**Issue by akiarostami** [chakra-ui/chakra-ui#1225]
**Describe the bug** A clear and concise description of what the bug is.

In Drawer (and possibly Modal), when **scrollBehavior** is set to **"inside"**, Drawer doesn't fill the height of the screen.

**Expected Behavior** A clear and concise description of what you expected to
happen.

Drawer, when opened from sides, should completely fill the heights of the screen, even with scrollBehavior set to "inside"

**Steps to Reproduce** Clear and concise reproduction instructions are important
for us to be able to triage your issue in a timely manner.

Use this line:

```
<Drawer isOpen={isOpen} placement="right" onClose={onClose} size="sm" scrollBehavior="inside">
...
</Drawer>
```

**Suggested solution(s)**

in **modal.js, line 28**, we have

`maxHeight: props.scrollBehavior === 'inside' ? 'calc(100vh - 7.5rem)' : undefined`

This is the cause of the issue. I don't know why we have that 7.5rem there, perhaps it has something to do with Modals, but it's breaking the Drawer.

Can we remove this line?!

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version latest

**Comment by segunadebayo** [comment]
I agree @akiarostami. Thanks for catching that.

This has been fixed in v1 by isolating the drawer and modal styles/components.

v1 will be public by next week so you can get the fixes. If you can send a Codesandbox repro of this issue, I can suggest a temporary walkaround.

**Comment by akiarostami** [comment]
Hi @segunadebayo,

I was wondering if you have an update for the v1 release?

**Comment by with-heart** [comment]
Hi @akiarostami! This is fixed in `1.0.0-rc.0`. https://codesandbox.io/s/vibrant-dhawan-zkhzf?file=/src/App.tsx

**Comment by akiarostami** [comment]
Thank you @with-heart. However, the link you sent still shows the same error.

Beside this issue, I'm interested to know when v1 will be released. Thank you.

**Comment by with-heart** [comment]
Wow, when I posted that link it was working. I refreshed the tab and now it's incorrect. Not sure what happened there.

It'll be released when it's released basically 😆

**Comment by with-heart** [comment]
Interesting. It looks like separate `Drawer` theming was created, but it was never attached to `Drawer`. It's still using the `Modal` theming.

**Comment by akiarostami** [comment]
hahaha... that is a comming practice @with-heart, at least whenever I go to see my doctor, that happens! :) 

I understand the "release schedule", but since @segunadebayo said next week 2 weeks ago, I was wondering is there's an update.

**Comment by segunadebayo** [comment]
I've just pushed a fix for this @akiarostami. @with-heart you're right, the drawer wasn't connected to it's theming and I just did that.

It should work as expected now.

@akiarostami It's kinda tough to give a specific date. We're currently in the `rc` stage of v1 and this means we're getting pretty close to `v1`. I believe we'll get it stable over the coming weeks.

**Comment by rodbs** [comment]
@akiarostami Not sure if this is related but I cannot get the drawer to fill the height of the screen, but only on mobile (with scrollBehavior  or w/o) (In rc.2). Is there any additional option to expand it?
https://igls-next-firebase.vercel.app/
 
In this file it seems that the height is fixed to 100vh. Is it right?
https://github.com/chakra-ui/chakra-ui/blob/af613020125265914a9dcb74c92a07a16aa4ff8e/packages/theme/src/components/drawer.ts
