### ISSUE TITLE
Yarn 2 (Plug n' Play) exposes dependency inconsistencies

### ISSUE THREAD

**Issue by beforan** [chakra-ui/chakra-ui#1443]
Yarn 2 (in default Plug n' Play mode, not using `node_modules`) is much stricter around package dependencies.

Trying to use chakra in such an environment causes the following sorts of errors:

```
Module not found: Error: @chakra-ui/number-input tried to access @chakra-ui/hooks, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

**Expected Behavior**

`Module not found` errors should not occur when building projects using Chakra in a Yarn 2 Plug n' Play environment.

**Link to minimal reproduction**
https://github.com/beforan/chrakra-ui-v1-yarn2

Sorry it's not super minimal (as a repo) but I think the environment is important, and useful to showcase the issue and fix.

It's a brand new CRA app, with all the starter stuff removed and chakra `1.0.0-rc.0` added, and that's all. It also has storybook.

**Steps to Reproduce**

1. Have yarn globally installed (`npm i -g yarn` is recommended by yarn2's docs, but i believe any yarn install is fine)
    - it will run the repo's local yarn 2 binary
1. Run `yarn` to install dependencies
1. Run any of the following to see the errors:
    - `yarn start`
    - `yarn build`
    - `yarn storybook`

`storybook` is useful here as it throws all the errors at once; `start` and `build` seem to do it one by one. Some difference in how storybook and react-scripts invoke webpack, i guess.

This repo also showcases the current workaround (as described [here](https://github.com/beforan/chrakra-ui-v1-yarn2)):

1. Add `packageExtensions` to `.yarnrc.yml` to tell yarn about the missing dependencies.
    - I have done this in this repo, but they are commented out. this should highlight which dependencies need adding.

It also shows some peer dependencies which are installed in the local project, so I'm not sure of the cause of that, but it may warrant investigation. These are also noted in the `.yarnrc.yml`

**Suggested solution(s)**

Add the missing dependencies to the relevant packages:

```
"@chakra-ui/css-reset@1.0.0-rc.0":
  dependencies:
    "@emotion/core": "^10.0.28"
"@chakra-ui/core@1.0.0-rc.0":
  dependencies:
    "@chakra-ui/transition": "1.0.0-rc.0"
"@chakra-ui/drawer@1.0.0-rc.0":
  dependencies:
    "@chakra-ui/utils": "1.0.0-rc.0"
"@chakra-ui/number-input@1.0.0-rc.0":
  dependencies:
     "@chakra-ui/hooks": "1.0.0-rc.0"
```

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows 10 2004
- Browser [e.g. chrome, safari] chrome, edge
- Version [e.g. 22] of browser? 84

**Additional context**
I came across it playing with Yarn2.

It occurs to me that the environments I've encountered that show the errors are webpack based (CRA, storybook), though it is definitely Yarn's PNP environment, not webpack itself that's responsible, as per Yarn2's documentation, so I don't think that's of note.

**Comment by with-heart** [comment]
Solid investigation! Thanks for letting us know.

I'm surprised it took someone using Yarn2 to discover this! I wonder if there's a way we can reliably detect dependency inconsistencies like this. We could add that to our GitHub Actions workflows if so.

**Comment by beforan** [comment]
Well (as I understand it) npm, and yarn when using `node_modules`, is "optimistic" and just assumes that if the dependency is in the workspace, then so what, that's fine. So a lot of package are probably not quite right, but get away with it. I suspect this is very often the case in monorepos where any dependency hoisting can make it extra unclear what belongs with which packages.

Yarn's plug n play mode is much better at analysing dependencies, and is therefore much stricter.

Re: the peer dependencies, I think this might be cases where a Chakra dependencies declares a peer that Chakra then doesn't fulfill. 

That would explain why adding it as a dependency of that Chakra package (using packageExtensions) resolves things; the Chakra package is then effectively fulfilling the peer dependency of its regular dependency.

I'm not sure how many of those cases want the peer dependency fulfilled by the Chakra package though, or if that should be passed on to the consumer of Chakra.

e.g. if it's `react-dom` that's wanted, then that's practically guaranteed to be provided at the top level app. but yarn still seems to warn (as is the case in the repo linked in the issue). Not 

Those warnings aren't showstopping though, so ¯\_(ツ)_/¯

**Comment by PierreAndreis** [comment]
I suspect it is just the nature of npm. It used to be that by default, `npm install xyz` did not add xyz to package.json.
Which is weird behavior in my opinion.

**Comment by beforan** [comment]
yeah, but that was about 3 years ago, and they changed it after Yarn's first release saved on install by default, and used a lock file. It's possible Yarn's behaviour on this will promote changes in other tooling again.

Regardless, the fact remains that some Chakra packages aren't fully transparent about their dependencies, even though they luckily work in practice. And users of Yarn 2 will have to manually work around it unless it is fixed in the packages themselves.

**Comment by segunadebayo** [comment]
Thank you for this issue @beforan.

Looking into it.

**Comment by segunadebayo** [comment]
I just fixed these issues and will release an update shortly.

Thank you!

**Comment by BasixKOR** [comment]
This issue still persists with `@chakra-ui/css-reset`. Could we open this issue again?

**Comment by bodazhao** [comment]
Dependency error is breaking for the get started snippet

![image](https://user-images.githubusercontent.com/6238558/98590809-45cf9380-22c7-11eb-9430-44b3ae0901d5.png)

This is from NPM v7

**Comment by segunadebayo** [comment]
@bodazhao, we fixed this issue in Chakra UI v1

I believe adding `manypkg` helped us fix this issue. Closing this.

**Comment by dlindenkreuz** [comment]
Still happens with `@chakra-ui/styled-system`:

```
error - .yarn/cache/@chakra-ui-styled-system-npm-1.4.1-7f44090863-1cd51ad9fc.zip/node_modules/@chakra-ui/styled-system/dist/esm/core/create-parser.js:2:0
Module not found: @chakra-ui/styled-system tried to access lodash.mergewith, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: lodash.mergewith (via "lodash.mergewith")
Required by: @chakra-ui/styled-system@npm:1.4.1
```

**Comment by gmathieu** [comment]
@dlindenkreuz upgrading to the latest versions of `@chakra-ui/styled-system` and `@chakra-ui/icon` seem to resolve the issue.

I've created a PR to address `@chakra-ui/toast` -> `@reach/alert` -> `@reach/visually-hidden` https://github.com/chakra-ui/chakra-ui/pull/3650

**Comment by GfxKai** [comment]
Just got the same error with `@chakra-ui/provider` after following the installation instructions in a new project.

I had to add the following missing dependencies to `.yarnrc.yml`:
```yml
packageExtensions:
  "@chakra-ui/provider@*":
    dependencies:
      "@chakra-ui/portal": 1.2.9
      "@chakra-ui/react-env": 1.0.6
```

**Comment by cameronbourgeois** [comment]
I have these chakra dependencies in my package.json

```
    "@chakra-ui/icons": "^1.0.15",
    "@chakra-ui/react": "^1.6.7",
    "@chakra-ui/theme-tools": "^1.2.0",
```

And I needed to add the following to my `.yarnrc.yml`:

```
packageExtensions:
  '@chakra-ui/provider@*':
    dependencies:
      '@chakra-ui/portal': '*'
      '@chakra-ui/react-env': '*'
  '@chakra-ui/icons@*':
    dependencies:
      '@chakra-ui/system': '*'
```

**Comment by nikosolihin** [comment]
Following Chakra's getting started page resulted in these deps in my package.json: 

```
"@chakra-ui/react": "^1.6.10",
"@emotion/react": "^11",
"@emotion/styled": "^11",
"framer-motion": "^4",
```

And I needed to add the following to `.yarnrc.yml`:

```
packageExtensions:
  "@chakra-ui/system@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/checkbox@*":
    dependencies:
      framer-motion: "*"
  "@chakra-ui/transition@*":
    dependencies:
      framer-motion: "*"

```

**Comment by Pagebakers** [comment]
Having similar issues with yarn3

```
➤ YN0002: │ @chakra-ui/accordion@npm:1.4.2 [0f71e] doesn't provide framer-motion (p9ce2f), requested by @chakra-ui/transition
➤ YN0002: │ @chakra-ui/accordion@npm:1.4.2 [863e7] doesn't provide framer-motion (pf937f), requested by @chakra-ui/transition
➤ YN0002: │ @chakra-ui/anatomy@npm:1.2.1 doesn't provide @chakra-ui/system (p2ef3e), requested by @chakra-ui/theme-tools
➤ YN0002: │ @chakra-ui/props-docs@npm:1.0.40 doesn't provide @emotion/react (p3f1ef), requested by @chakra-ui/react
➤ YN0002: │ @chakra-ui/props-docs@npm:1.0.40 doesn't provide @emotion/styled (p2430d), requested by @chakra-ui/react
➤ YN0002: │ @chakra-ui/props-docs@npm:1.0.40 doesn't provide framer-motion (pab794), requested by @chakra-ui/react
➤ YN0002: │ @chakra-ui/props-docs@npm:1.0.40 doesn't provide react (pb8f77), requested by @chakra-ui/react
➤ YN0002: │ @chakra-ui/props-docs@npm:1.0.40 doesn't provide react-dom (p5d945), requested by @chakra-ui/react
➤ YN0002: │ @chakra-ui/skeleton@npm:1.2.2 [b0905] doesn't provide @chakra-ui/theme (pfb39f), requested by @chakra-ui/media-query
➤ YN0002: │ @chakra-ui/skeleton@npm:1.2.3 [863e7] doesn't provide @chakra-ui/theme (pd9969), requested by @chakra-ui/media-query
➤ YN0002: │ @chakra-ui/skeleton@npm:1.2.3 [863e7] doesn't provide @emotion/react (p8a157), requested by @chakra-ui/system
➤ YN0002: │ @chakra-ui/skeleton@npm:1.2.3 [863e7] doesn't provide @emotion/styled (pf6eb8), requested by @chakra-ui/system
➤ YN0002: │ @chakra-ui/switch@npm:1.3.1 [0f71e] doesn't provide framer-motion (pa9960), requested by @chakra-ui/checkbox
➤ YN0002: │ @chakra-ui/switch@npm:1.3.1 [863e7] doesn't provide framer-motion (p94192), requested by @chakra-ui/checkbox
```

**Comment by Poolshark** [comment]
I also still have the same issue as @Pagebakers with Yarn 3... Pretty much the entire dependency tree is not getting found! 

Any updates on this issue? I don't want to fix the entire dependency tree for Chakra inside the `yarnrc.yml`...

**Comment by bajcmartinez** [comment]
Same issues here:

ERROR in ../../.yarn/__virtual__/@chakra-ui-spinner-virtual-1a33bfe64c/0/cache/@chakra-ui-spinner-npm-2.0.0-6794a62c0b-c97cc81342.zip/node_modules/@chakra-ui/spinner/dist/chakra-ui-spinner.esm.js 40:11-20

export 'keyframes' (imported as 'keyframes') was not found in '@chakra-ui/system' (possible exports: CSSVars, ColorModeContext, ColorModeProvider, ColorModeScript, DarkMode, GlobalStyle, LightMode, STORAGE_KEY, StylesProvider, ThemeProvider, addPrefix, background, border, calc, chakra, color, cookieStorageManager, createCookieStorageManager, createLocalStorageManager, css, cssVar, effect, filter, flattenTokens, flexbox, forwardRef, getCss, getScriptSrc, grid, interactivity, isStyleProp, layout, layoutPropNames, list, localStorageManager, omitThemingProps, others, position, propNames, pseudoPropNames, pseudoSelectors, ring, scroll, shouldForwardProp, space, styled, systemProps, textDecoration, toCSSObject, toCSSVar, toVarDefinition, toVarReference, tokenToCSSVar, transform, transition, typography, useChakra, useColorMode, useColorModeValue, useMultiStyleConfig, useProps, useStyleConfig, useStyles, useTheme, useToken)


ERROR in ../../.yarn/__virtual__/@chakra-ui-system-virtual-71df89ac0d/0/cache/@chakra-ui-system-npm-2.0.0-f7043a57d8-58e7da023f.zip/node_modules/@chakra-ui/system/dist/chakra-ui-system.esm.js 5:0-88

Module not found: Error: @chakra-ui/system tried to access @emotion/react (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.


Anyone has any ideas?

**Comment by misterjame** [comment]
+1
