### ISSUE TITLE
Request to add 'filter' prop to the Box component

### ISSUE THREAD

**Issue by kckusal** [chakra-ui/chakra-ui#1504]
## What problem does this feature solve?
Currently, as I have tried, I cannot use the prop **filter** in any Chakra components. Adding _filter_ prop allows the CSS **filter** property to be used to apply graphical effects like blur or color shift to an element. Filters are commonly used to adjust the rendering of images, backgrounds, and borders.

### Additional context
Here's more about the [CSS filter property](https://developer.mozilla.org/en-US/docs/Web/CSS/filter).

**Comment by segunadebayo** [comment]
Hey @kckusal,

Given that `Box` component is also a normal React component. You can pass the `style` prop to apply this property.

```jsx
<Box style={{ filter:  "blur(5px)" }} />
```

At the moment, we're careful not to add all possible CSS props. Consider the `style` prop an alternative to one-off custom styles.

Hope this helps.

**Comment by gbrlsnchs** [comment]
Hey, @segunadebayo, first of all, thanks for this awesome library.

Using `style` prop as suggested doesn't seem to work with `_hover` (when using a `PseudoBox`, of course), while using `_hover={{ filter: "..." }}` works, but triggers a TypeScript compile-time error. Currently I can use it with the error since I'm using Gatsby, but some folks might have some trouble if depending on the code to fully work with TypeScript.

**Comment by ljosberinn** [comment]
@gbrlsnchs this issue is fixed in v1 and won't cause a TS error either anymore :)

**Comment by gbrlsnchs** [comment]
@ljosberinn Thanks for the heads-up! You folks rock.

**Comment by gbrlsnchs** [comment]
@ljosberinn, I tried version `1.0.0-rc.5`, and it seems `filter` is still missing in `_groupHover` options.

**Comment by gbrlsnchs** [comment]
Also, when I use `filter` on `Image`, Chakra adds it as a style element, not a CSS property.
