### ISSUE TITLE
[Checkbox] React does not recognize the `isChecked` prop on a DOM element

### ISSUE THREAD

**Issue by neighborhood999** [chakra-ui/chakra-ui#1589]
After upgrade to 1.0.0-rc.2 got this error messages:

```
React does not recognize the `isChecked` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ischecked` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

...

React does not recognize the `isIndeterminate` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isindeterminate` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

**Comment by ljosberinn** [comment]
Hi, can you show the code that led to this?

**Comment by neighborhood999** [comment]
> Hi, can you show the code that led to this?

Sure!, see the below:

```jsx
<Stack direction="row" spacing="5" my="3">
	<Checkbox>Checkbox</Checkbox>
	<Checkbox defaultIsChecked>Checkbox</Checkbox>

	<Checkbox isDisabled>Checkbox</Checkbox>
	<Checkbox isDisabled defaultIsChecked>
		Checkbox
	</Checkbox>

	<Checkbox isInvalid>Checkbox</Checkbox>
</Stack>
```

Not sure what's going on..., I upgrade to rc.1 in the past days and it works fine.

**Comment by with-heart** [comment]
Looks like it happened here: https://github.com/chakra-ui/chakra-ui/commit/3828ea633f8ce72c7f3b7cbbf4579b123b165e9a#diff-83ce84c6340973dc82434d31745acdcd

`Icon` should receive `...rest`, not all of the props. Will fix.

**Comment by ljosberinn** [comment]
ah on the CheckboxIcon! I was looking on the Checkbox and wondered 😅

**Comment by with-heart** [comment]
It took me a bit to realize it was a separate component 🙃

**Comment by dusanstojanovic** [comment]
Is this fixed in `1.0.0-rc.2`? I'm getting same errors

**Comment by ljosberinn** [comment]
No, it will be in the next release.

**Comment by mmesarosiuSP** [comment]
Hello,

I still encounter this warning on `"@chakra-ui/react": "^2.2.1"` only when using a custom icon.
Reproducible example:

``` 
<Checkbox
     color="neutral.300"
     isChecked={isChecked}
     icon={<Icon icon={faCheck} w={2} h={1.5} />}
     justifyContent="space-between"
     size="sm">
    Subscribe
</Checkbox>
```

**Comment by mathesond2** [comment]
I'm getting this as well in my new implementation:
```jsx
<Checkbox
   icon={<ViewIcon />}
   iconColor="red.500"
   onChange={() => {}}
>
   check me
</Checkbox>
```

![Screen Shot 2022-11-30 at 3 32 31 PM](https://user-images.githubusercontent.com/5042175/204902241-b3f3a666-c86d-4499-96f2-b5251c526f25.png)
