### ISSUE TITLE
Failing to compile: Chakra UI + Framer Motion in typescript 

### ISSUE THREAD

**Issue by zzal** [chakra-ui/chakra-ui#1814]
I'm trying to use Framer Motion for page transitions, but when using the `motion.custom(Box)` as described in the documented pull request: [https://github.com/chakra-ui/chakra-ui/issues/669](https://github.com/chakra-ui/chakra-ui/issues/669), I end up with a conflict with the property `transition` that is present in both `Box` and `motion.custom`.

```
Error:(26, 7) TS2322: Type 'Transition' is not assignable to type '("initial" & Orchestration & Tween) | ("initial" & Orchestration & Spring) | ("initial" & Orchestration & Keyframes) | ... 133 more ... | undefined'.
  Type 'Orchestration & Tween' is not assignable to type '("initial" & Orchestration & Tween) | ("initial" & Orchestration & Spring) | ("initial" & Orchestration & Keyframes) | ... 133 more ... | undefined'.
    Type 'Orchestration & Tween' is not assignable to type '{ [x: string]: "initial" | "inherit" | "-moz-initial" | "revert" | "unset" | "none" | (string & {}) | "all" | "ease" | "ease-in" | "ease-in-out" | "ease-out" | "step-end" | "step-start" | "linear" | undefined; [x: number]: "initial" | ... 14 more ... | undefined; } & Orchestration & { ...; }'.
      Type 'Orchestration & Tween' is not assignable to type '{ [x: string]: "initial" | "inherit" | "-moz-initial" | "revert" | "unset" | "none" | (string & {}) | "all" | "ease" | "ease-in" | "ease-in-out" | "ease-out" | "step-end" | "step-start" | "linear" | undefined; [x: number]: "initial" | ... 14 more ... | undefined; }'.
        Index signature is missing in type 'Orchestration & Tween'.  TS2322

    24 |       exit="out"
    25 |       variants={pageVariants}
  > 26 |       transition={pageTransition}
       |       ^
    27 |     >
```

Here's a code example:

```typescript
…
import { motion } from 'framer-motion';
import { Box, Text } from '@chakra-ui/core';
import { pageVariants, pageTransition } from '../constants';

const MotionBox = motion.custom(Box);

const MyView = (): JSX.Element => (
<MotionBox
      className="my-view"
      initial="initial"
      animate="in"
      exit="out"
      variants={pageVariants}
      transition={pageTransition}
    >
      <Text>Hello World</Text>
</MotionBox>
);
…
```

Since both `Box` and `motion.custom` have a `transition` property, I think, there is a conflict.

Can I specify `Box` with omitted `transition` property?

I know I could wrap my `<Box>` element into a `<motion.div>`, but I would prefer not doing so. (or I could i set its `<motion.div style={{ display: 'contents' }}>`, so my layout wouldn't explose but then no animation could be applied, which defy the purpose…)

**Comment by segunadebayo** [comment]
Hi @zzal, thanks for reporting this.

We've fixed this in the upcoming v1 version.  It'll be released shortly so you can get your hands on it.
https://github.com/chakra-ui/chakra-ui/blob/develop/packages/system/stories/system.stories.tsx

Cheers.

**Comment by jgillich** [comment]
Seems like this issue is back (unless I'm missing something)
```typescript
const MotionBox = motion<BoxProps>(Box)
<MotionBox
  animate={{backgroundColor: ['#38A169', '#38A169']}}
  transition={{duration: 1, repeat: Infinity, repeatType: 'reverse'}} />
```
```
Type '{ duration: number; repeat: number; repeatType: "reverse"; }' is not assignable to type '(ResponsiveValue<Transition<string & {}>> & Transition) | undefined'.
  Type '{ duration: number; repeat: number; repeatType: "reverse"; }' is not assignable to type 'undefined'.ts(2322)
```

**Comment by iAmAdamReid** [comment]
> Seems like this issue is back (unless I'm missing something)
> 
> ```ts
> const MotionBox = motion<BoxProps>(Box)
> <MotionBox
>   animate={{backgroundColor: ['#38A169', '#38A169']}}
>   transition={{duration: 1, repeat: Infinity, repeatType: 'reverse'}} />
> ```
> 
> ```
> Type '{ duration: number; repeat: number; repeatType: "reverse"; }' is not assignable to type '(ResponsiveValue<Transition<string & {}>> & Transition) | undefined'.
>   Type '{ duration: number; repeat: number; repeatType: "reverse"; }' is not assignable to type 'undefined'.ts(2322)
> ```

Yeah, it looks like there's a conflict between the `Box` transition prop and the `motion` transition prop that happens when the two prop types are merged.

If you want to get around the compilation error, you can use the `<Omit>` helper in TypeScript to alleviate the conflict until this is fixed:

```
const MotionBox = motion<Omit<BoxProps, "transition">>(Box);
```

**Comment by oncet** [comment]
Suggested workaround by @iAmAdamReid  works but feels kinda obscure.

@segunadebayo are there any plans to fix this conflict?
