### ISSUE TITLE
[Tooltip] wrong placement and arrow positions

### ISSUE THREAD

**Issue by rafma0** [chakra-ui/chakra-ui#1863]
**Describe the bug**
In some cases tooltips don't seem to respect the placement ('bottom-start' showing in 'bottom-end' position, etc) and you can see the rotated square for the arrows, also the z-index for the squares seems to be higher than the label so depending on the size it will show on top

**Link to minimal reproduction**
https://codesandbox.io/s/youthful-burnell-k6460?file=/src/App.js

If you reduce codesandbox browser width you can see the tooltip for the 99% button jumping from right to left

removing resetCss from ChakraProvider and reloading codesandbox browser seems to fix the position for the labels but not for the arrows

**Comment by segunadebayo** [comment]
This has been fixed recently when we switched to `react-popper`. We'll release an update shortly.

**Comment by jackiewung** [comment]
@segunadebayo i see `react-popper` in the latest version but i'm still seeing an arrow placement bug on the latest version
