### ISSUE TITLE
[Popover][V1] Popover trigger render on scroll

### ISSUE THREAD

**Issue by hosmelq** [chakra-ui/chakra-ui#2091]
# Bug report

## Describe the bug

If I have a `popover` on the page every time I scroll the popover rerender.

## To reproduce

Scroll the page and you will see the counter increase.

## Minimal reproduction

[codesandbox](https://codesandbox.io/s/gracious-elbakyan-bftcb)

## Expected behavior

Do not trigger rerender on scroll.

## System information

- Version of @chakra-ui/core: [e.g. 1.0.0-rc.7]

**Comment by HarishJangra** [comment]
I am also having similar issue i.e.  when rendering multiple menu component  like 20. the scroll lags very much . May be it is related to this.
the same goes with popover instead of menu.

**Comment by nghieptiki** [comment]
Same issue 😭

**Comment by ljosberinn** [comment]
`PopoverContent` seems to be the issue here, even without anything in there it rerenders on scroll. This _may_ already be fixed due to the migration to `usePopper`, gotta check.

**Comment by TimKolberger** [comment]
_chakra-ui_ handles the visibility of the Tooltip/Popover/etc with `useDisclosure` and animate the transition on our own with _motion_. _react-popper_ does not know if its content is visible or not, and rerenders always.

To fix this issue _react-popper_ needs the functionality to stop updating its styles if the using side (e.g. _chakra-ui_) does not need the update to happen.

**More context:**

### Usage of `usePopper` (renamed to `useBasePopper`) in _chakra-ui_

https://github.com/chakra-ui/chakra-ui/blob/54ff9e8105fdce379059b4480203143309ef4aef/packages/popper/src/use-popper.ts#L127-L131

> rerenders on scroll

#### Replace popperJS with a mock

```ts
const popperJS = { attributes: {}, styles: {} } as any
```

> does NOT rerender on scroll

I tried setting the `referenceNode` and `popperNode` conditionally to null, if the content is not visible, but it led to awkward behaviour.

### Source of the rerender in `usePopper` in _react-popper_

The `setState` call triggers the rerender:

https://github.com/popperjs/react-popper/blob/68a992c07dc145935acbe682fa496f888136e55c/src/usePopper.js#L52-L72

**Comment by segunadebayo** [comment]
Great investigation @TimKolberger and @ljosberinn. Taking a look at this, perhaps we might have to maintain our custom `usePopper` hook to manage the state updates.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. Thanks for catching that @hosmelq

**Comment by nghiepit** [comment]
@segunadebayo 
Has the fix been released yet? 
I'm had tried `1.0.0-rc.8` but the issue is still.

**Comment by patresk** [comment]
Unfortunately, I don't think this was fixed, we are experiencing the same issue in `chakra-ui/react@1.6.6`. We temporarily hotfixed it with

```
eventListeners={{
  scroll: false,
}}
```

to every Popover. This degrades the UX a little bit, but the performance benefit is large.
