### ISSUE TITLE
[ Typescript]: MenuButton component's  `rightIcon` prop  does not have a type

### ISSUE THREAD

**Issue by ameerkabir** [chakra-ui/chakra-ui#2110]
# Feature request

## Is your feature request related to a problem? Please describe.

- Passing `rightIcon` prop to a`MenuBtton`  causes Typescript error.
## Describe the solution you'd like

- I would be great to have `rightIcon` props listed on `MenuButton's` types
## Describe alternatives you've considered

- The work around is to add `@ts-ignore` ignore so Typescript can stop complaining.

## Additional context
* The screenshot shows the uses of `rightIcone` prop on a `MenuButton`

![image](https://user-images.githubusercontent.com/11903040/94426943-3caabd00-0186-11eb-9458-7647fa2b46da.png);

---

* Screenshot for the actual typescript error message
![image](https://user-images.githubusercontent.com/11903040/94427098-767bc380-0186-11eb-97f5-600e5ef98121.png)

---

* link to the interactive example https://codesandbox.io/s/eloquent-meitner-wikek

**Comment by ljosberinn** [comment]
Hi, looks like this is one of the shortcomings of `v0.7` which you're on. I'd recommend upgrading to `v0.8`. If the issue persits there I'm afraid you'll have to stick to `@ts-expect-error` here as this is fixed in `v1` as `v0.x` will not receive further updates.

See https://codesandbox.io/s/objective-lamarr-oz5e4?file=/src/App.js for a v1 version.

**Comment by ameerkabir** [comment]
@ljosberinn Thank you, will give that a go.

**Comment by ameerkabir** [comment]
> Hi, looks like this is one of the shortcomings of `v0.7` which you're on. I'd recommend upgrading to `v0.8`. If the issue persits there I'm afraid you'll have to stick to `@ts-expect-error` here as this is fixed in `v1` as `v0.x` will not receive further updates.
> 
> See https://codesandbox.io/s/objective-lamarr-oz5e4?file=/src/App.js for a v1 version.

So I can confirm that we are on the latest version

![image](https://user-images.githubusercontent.com/11903040/94443440-15131f00-019d-11eb-9c94-18cd1c3ae8fe.png)

and the issue still exists

**Comment by ameerkabir** [comment]
An update on this issue, We have fix this issue by type casting the chakra component;

Here is the screenshot to the solution 

![image](https://user-images.githubusercontent.com/11903040/94548599-df2b7480-0248-11eb-9e7c-613e42393b04.png)

--
![image](https://user-images.githubusercontent.com/11903040/94548987-6e388c80-0249-11eb-8cde-c3f754f0860e.png)


- Just make sure you import `MenuButtonProps` & `ButtonProps`
