### ISSUE TITLE
Accordion (when used as filterable list of items) is stealing focus from input field.

### ISSUE THREAD

**Issue by sebqq** [chakra-ui/chakra-ui#2160]
# Bug report

## Describe the bug

My use case includes using Accordion as list of filterable items. List is filtered by Input field's value. When I opened any of accordion items and after that I try to filter items byt input field, It often happens that accordion steals focus from input field, which directly leads to poor UX. Is there something I can do about it? Thanks!

You can see my problem at following gif video:
![2020-10-04 14 07 25](https://user-images.githubusercontent.com/33039909/95015080-57c87180-064b-11eb-9d53-779522e18fe7.gif)

## To reproduce

When I opened any of accordion items and after that I try to filter items byt input field, It often happens that accordion steals focus from input field, which directly leads to poor UX. Is there something I can do about it? Thanks!

## Minimal reproduction

I've prepared following [codesandox demo](https://codesandbox.io/s/wild-http-1p3iw?file=/src/components/Searcher.js)

## Expected behavior

Focus should stay on Input. 

## System information

- OS: macos
- Version of @chakra-ui/core: 1.0.0-rc.5

**Comment by ljosberinn** [comment]
Probably related to [this](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/accordion/src/use-accordion.ts#L214) line calling `useFocusEffect`, because the issue doesn't only replicate given the element that was visible before, but also just any other that matches the same position as before filtering.

I wonder whether this has something to do with `useUpdateEffect`, which doesn't set `mounted.current` to `false` when unmounted here, becasue else I wouldn't know how an unmounted component can retain its state after rerendering.
https://github.com/chakra-ui/chakra-ui/blob/afdd211a0fca8c71ce800dc11a83b338aefa15ef/packages/hooks/src/use-update-effect.ts#L14

**Comment by segunadebayo** [comment]
Thanks for taking a look @ljosberinn.

This is happening because we didn't clean up or reset the `focusedIndex` when accordion unmounts or accordion items change. I just pushed a fix for this.

@sebqq, you might need to conditionally render the accordion as well using this:

```jsx
 {displayData.length > 0 && (
        <Accordion allowToggle>
          {displayData.map((item, i) => {
            return (
              <AccordionItem key={`accordion-item-${i}`}>
                <AccordionButton>
                  <Box flex="1" textAlign="left">
                    {item.title}
                  </Box>
                  <AccordionIcon />
                </AccordionButton>
                <AccordionPanel pb={4}>{item.text}</AccordionPanel>
              </AccordionItem>
            );
          })}
        </Accordion>
      )}
```

We'll release an update shortly.

**Comment by sebqq** [comment]
@segunadebayo Hello and thanks for your response! Sadly, conditional rendering doesn't solve my issue for now. Should I wait for a new release to see a difference?
