### ISSUE TITLE
Menu component broken on page load

### ISSUE THREAD

**Issue by ChasinHues** [chakra-ui/chakra-ui#2323]
# Bug report

## Describe the bug

On page load, before resizing the browser or scrolling, clicking on menu buttons does not show the menu. 

## To reproduce

1. Go to https://next.chakra-ui.com/docs/overlay/menu
2. Scroll down to a menu button.
3. Refresh the page (Note: might need to refresh twice).
4. Before scrolling/resizing the browser, try and click on the menu button.
5. Observe: button appears to have been clicked but menu does not open.
6. If you scroll a bit or resize the window, the menu fixes itself and works as expected.

## Expected behavior

Clicking on the menu button at any time should toggle the menu.

## System information

- OS: MacOS Catalina 10.15.7
- Browser (if applies): Chrome (tried Safari but it auto-scrolls down to where you left off so couldn't reproduce here)
- Version of @chakra-ui/core: 1.0.0-rc.7

**Comment by ljosberinn** [comment]
Does this happen for you in your project too? Works fine for me on my site with a Menu within Header.

**Comment by segunadebayo** [comment]
This might be related to popperJS and the `usePopper` hook we're using from there.

**Comment by ChasinHues** [comment]
Strangely not experiencing this in our project. In our case I noticed the menu is loaded before other parts of our app, so as other components load after it the menu gets bumped around a bit. 

I didn't experience this issue in Safari (testing Chakra website), potentially because Safari scrolls down to where you refreshed the page. Seems like the act of scrolling or resizing the page trigger some extra logic to run that causes the menu to behave as expected.

**Comment by gifaeriyanto** [comment]
I tried to zoom out my screen until 50% and I got this:
![image](https://user-images.githubusercontent.com/6601377/97215295-38aea100-17ff-11eb-876b-4590558f0f8a.png)

Seems the menulist  `transform translate` has a wrong value. I tried in the storybook and the menu works correctly, maybe this just happens on the doc website. CMIIW

**Comment by ChasinHues** [comment]
@gifaeriyanto  I'm experiencing this behaviour with the new menu in our project as well. I thought it might have been something specific to how we were using it, but maybe not. See screenshot below. 

Also worth noting that this behaviour we're experiencing with the menu position seems to only be on page load before any window resize/scroll events, as these events seem to correct the positioning of the menu.

![image](https://user-images.githubusercontent.com/13565648/97233517-d075b480-182a-11eb-9e42-9cd7ae7ce730.png)

#### Implementation (minus extraneous styles)

```
            <Menu placement="bottom">
                <MenuButton
                    as={Button}
                    rightIcon={<BsChevronDown />}
                    width="100%"
                >
                    {activeItem ? activeItem?.displayText : "Where would you like to go?"}
                </MenuButton>
                <MenuList 
                    width="100vw" // NOTE: To make menu full width of screen. `w='100%'` worked prior to RC7.
                >
                    {enabledItems.length > 0
                        ? enabledItems.map((item, index) => (
                              <MenuItem as={NavLink} to={item.url} key={index}>
                                  {item.displayText}
                              </MenuItem>
                          ))
                        : null}
                    {enabledItems.length > 0 && disabledItems.length > 0 ? <MenuDivider /> : null}
                    {disabledItems.length > 0 ? (
                        <MenuGroup title="Register to view more">
                            {disabledItems.map((item, index) => (
                                <MenuItem as={NavLink} to={item.url} isDisabled key={index}>
                                    {item.displayText}
                                </MenuItem>
                            ))}
                        </MenuGroup>
                    ) : null}
                </MenuList>
            </Menu>
```

**Comment by segunadebayo** [comment]
Thanks for catching this @ChasinHues. I just pushed a fix for this and we'll release a new `rc` shortly

**Comment by ChasinHues** [comment]
FYI @segunadebayo just tried updating to rc8 and I'm still encountering this issue. The bug persists on the Chakra website as well https://next.chakra-ui.com/docs/overlay/menu

**Comment by ChiaJune** [comment]
same here
