### ISSUE TITLE
Nested Collapse not working properly

### ISSUE THREAD

**Issue by FabianFinke** [chakra-ui/chakra-ui#2396]
# Bug report

## Describe the bug

When nesting Collapse all subsequent collapse components are expanded when triggering the parent collapse.

## To reproduce

- Click on "Open 1" in the code sandbox or put a Collapse inside another Collapse and open the parent one.

## Minimal reproduction

https://codesandbox.io/s/confident-bird-t1wxm?file=/src/App.tsx

## Expected behavior

Nested collapse components should not be expanded if isOpen is false. If you click "Open 2" twice before "Open 1" it actually switches to the right behavior.

## System information

- Version of @chakra-ui/core: 1.0.0-rc.8

**Comment by segunadebayo** [comment]
Thanks for catching this @FabianFinke.

I just pushed a fix for it. It'll be released soon.

**Comment by Rezaabdi78** [comment]
hi Segun, Have you released the fix? bc I'm still encountering the same problem as @FabianFinke mentioned above.

**Comment by harshan89** [comment]
> Thanks for catching this @FabianFinke.
> 
> I just pushed a fix for it. It'll be released soon.

Seems still this not working.

**Comment by caelinsutch** [comment]
This seems to still not be fixed
