### ISSUE TITLE
Performance issue using <Menu /> when scrolling

### ISSUE THREAD

**Issue by gmathieu** [chakra-ui/chakra-ui#2531]
# Bug report

## Describe the bug

When closed, `<MenuList/>` re-calculates its position on scroll. This greatly impacts performance when lots of `<Menu />` components are rendered at once. This scenario is common when rendering tables/lists where each item has associated options. The `isLazy` prop, [mentioned here](https://github.com/chakra-ui/chakra-ui/issues/2415), helps but doesn't solve the issue.

## Minimal reproduction

1. https://codesandbox.io/s/chakra-uireact100-menu-perf-dejjg?file=/src/index.tsx
1. enable "Highlight updates when components render." in React DevTools<img width="1349" alt="Screen Shot 2020-11-16 at 10 02 35" src="https://user-images.githubusercontent.com/7855/99290312-fae7db80-27f2-11eb-9b8e-87786245de69.png">
1. scroll right pane

## Expected behavior

When scrolling, `<MenuList />` should only re-calculate its position if it is open.

## Screenshots

<img width="1465" alt="Screen Shot 2020-11-16 at 10 08 18" src="https://user-images.githubusercontent.com/7855/99290876-c9234480-27f3-11eb-97f8-5e9b4e2d441c.png">

## System information

- OS: macOS
- Browser (if applies): Chrome, Safari
- Version of @chakra-ui/react: 1.0.0, 1.0.1

**Comment by cereallarceny** [comment]
@with-heart I'm actually also having this, except the issue for me is a lot more pernicious. I get the following warning whenever I scroll or resize my window:

```
Popper: CSS "margin" styles cannot be used to apply padding between the popper and its reference element or boundary. To replicate margin, use the `offset` modifier, as well as the `padding` option in the `preventOverflow` and `flip` modifiers.
```

As you can imagine, receiving thousands of messages in less than a second crashes my window, thus making the `<Menu>` component, or the `<Popover>` component, completely unusable to me.

**Comment by cereallarceny** [comment]
@with-heart Might I suggest this project? https://github.com/chakra-ui/chakra-ui/projects/5

**Comment by kxxoling** [comment]
I'm also suffering this. In my case, I have a list of 20 items, in which have a Menu component. The whole page would crash if I scroll it quickly.
I'm using Lenovo yoga 14s with 16GB memory and AMD 4800u, just FYI.

**Comment by prayogoa** [comment]
We are also facing this issue with `Popover` (any chakra component that uses `usePopper` will have this issue really). The problem is with each popper instance being always "on" and listening to the dom scroll event even when the popover is not open.

The [event listeners](https://popper.js.org/docs/v2/modifiers/event-listeners/) default modifier is responsible for this, and turning scroll events off by passing `modifiers={{ name: 'eventListeners', options: { scroll: false }}` helped alleviate the issue.

**Comment by heikomat** [comment]
We still have this issue (the exact same behaviour as described by @prayogoa) with the latest version of the chakra-ui packages.

when scrolling, everything that uses a popover listens to scroll events, and checks its own position all the time. only adding the modifier as described by @prayogoa helps.

i suggest chakra cloud by default disable the scroll-eventlistener if `enabled = false`, or something like that

**Comment by prayogoa** [comment]
Yeah, we tried 1.1.5 which contains popover v1.1.7, but the issue still exists. The performance is much better when passing modifiers={{ name: 'eventListeners', options: { scroll: false }}` to `Popover` so https://github.com/chakra-ui/chakra-ui/pull/3022 did not fully fix the issue

**Comment by doender** [comment]
What I’ve noticed is that there seems to be a performance difference between dev and production builds when having many popovers/menus: in prod scrolling is a lot smoother in my application.

**Comment by dodas** [comment]
Hey guys,

I made a [PR](https://github.com/chakra-ui/chakra-ui/pull/3343) to create Popper.js instance only once it is needed (when menu is open) that should fix this hopefully.
I honestly can't feel any slowness after the first fix. Could you please try to reproduce the issue in [this version of the docs](https://chakra-ui-git-fork-dodas-fix-menu-scroll-perf.chakra-ui.now.sh/docs/overlay/menu)?

@doender Performance difference between dev and prod builds is normal. React does a lot more checking in dev.

**Comment by NairiAreg** [comment]
I'm still having this kind of problem, even worse, mine is dropping not letting me scroll properly
