### ISSUE TITLE
Theming of border radius is ignored for Toast

### ISSUE THREAD

**Issue by afestbaum** [chakra-ui/chakra-ui#2579]
# Bug report

## Describe the bug

Using extendTheme I'm not able to either theme borderRadius of a Toast (aka Alert) component or the padding of the IconButton component. Those props seem to be "hard-coded" to the respective elements. For the IconButton this can be overriden on the component itself, but for toast I can't find a way to pass additional style props.

## Expected behavior

Theme props should have priority

**Comment by michelmattos** [comment]
The document need to be updated. The right name for border radius in the theme is `radii` and not `borderRadius`.

**Comment by ockam** [comment]
Hit the same issue. I can see my style on the style provider but it’s not applied to the toast/alert container.

Here’s my theme element:
```
export const Alert = {
  baseStyle: {
    container: {
      borderRadius: 'base',
    },
  },
  variants: {...},
}
```

**Comment by ockam** [comment]
And using the `radii` key doesn’t work either...

**Comment by Aguirregzz97** [comment]
Pls fix this x.x

**Comment by ivpusic** [comment]
Alert is multipart component, so you have to specify which parts of it you want to extend. example if you want to customize container:

```javascript
export const extendedTheme = extendTheme({
  config,
  components: {
    Alert: {
      parts: ['container'],
      baseStyle: {
        container: {
          borderRadius: 'lg',
        }
      },
    }
  }
});
```

for more info check here https://chakra-ui.com/docs/theming/component-style#styling-multipart-components

**Comment by luizcieslak** [comment]
Could anyone make it? I tried @ivpusic solution but no success here: https://codesandbox.io/s/chakra-toast-p9grp?file=/src/index.tsx

**Comment by lennerd** [comment]
This works for styling the border radii of tags.

``` ts
import { extendTheme, withDefaultColorScheme } from '@chakra-ui/react';

const theme = extendTheme({
    Tag: {
      sizes: {
        sm: {
          container: {
            borderRadius: 'sm',
          },
        },
        md: {
          container: {
            borderRadius: 'sm',
          },
        },
        lg: {
          container: {
            borderRadius: 'sm',
          },
        },
      },
    },
  },
});
```

**Comment by oleh-demkovych** [comment]
Someone find a way how to change `boxShadow` and `borderRadius` of the `Toast` or `Alert`?

**Comment by johannespein** [comment]
@lennerd it's also not working for me

**Comment by johannespein** [comment]
I provided the fix here

https://github.com/chakra-ui/chakra-ui/pull/6056#event-6644610449

**Comment by johannespein** [comment]
> ```
> const Tag = {
>   baseStyle: {
>     container: {
>       borderRadius: '20px',
>     }
>   },
>   defaultProps: {
>     variant: 'none'
>   }
> }
> ```

this should now be working

**Comment by DillyDaily** [comment]
Hi there! I'm still unable to style borderRadius of **Toast** via Alert component styling. Alert receives the borderRadius, but the styling is not passed along to the Toast component.

const baseStyle = definePartsStyle({
  title: {
    textStyle: 'body',
  },
  container: {
    borderRadius: 'none',
    border: '2px',
  },
  description: { textStyle: 'body' },
});

**Comment by kaiserfedor** [comment]
You can't style Toast by customising Alert theme because of it's hardcoded in [Toast component](https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/toast/src/toast.tsx#L55).

But you can pass your custom toast component to ChakraProvider. For example my toast component (it's almost 100% copypasted from chakra sources):
```
import {
  Alert,
  AlertTitle,
  Box,
  CloseButton,
  ToastProps,
} from '@chakra-ui/react';
import { CloseIcon } from '../../icons';

export function Toast(props: ToastProps) {
  const {
    status,
    variant = 'solid',
    id,
    title,
    isClosable,
    onClose,
    colorScheme,
  } = props;

  const ids = id
    ? {
        root: `toast-${id}`,
        title: `toast-${id}-title`,
        description: `toast-${id}-description`,
      }
    : undefined;

  return (
    <Alert
      addRole={false}
      status={status}
      variant={variant}
      id={ids?.root}
      colorScheme={colorScheme}
    >
      <Box flex="1" maxWidth="100%">
        {title && <AlertTitle id={ids?.title}>{title}</AlertTitle>}
      </Box>
      {isClosable && (
        <CloseButton
          as={CloseIcon}
          size="sm"
          onClick={onClose}
          position="absolute"
          fill="elements.secondary"
          top={4}
          right={4}
        />
      )}
    </Alert>
  );
}

```

Then pass it to your ChakraProvider
```
<ChakraProvider
        theme={theme}
        toastOptions={{
          defaultOptions: { position: 'top-right', render: Toast },
        }}
      >
// your app code
</ChakraProvider>
```

Now you can apply custom Alert theme:
```
import { alertAnatomy as parts } from '@chakra-ui/anatomy';
import { createMultiStyleConfigHelpers } from '@chakra-ui/styled-system';

const { definePartsStyle, defineMultiStyleConfig } =
  createMultiStyleConfigHelpers(parts.keys);

const baseStyle = definePartsStyle({
  container: {
    h: 14,
    alignItems: 'center',
    borderRadius: '2xl',
  },
  title: {
    color: 'white',
    fontWeight: 600,
  },
  description: {
    color: 'white',
  },
});

export const alertStyle = defineMultiStyleConfig({
  baseStyle,
  defaultProps: {
    variant: 'solid',
  },
});

```
