### ISSUE TITLE
NumberInput increment / decrement not relative to uncontrolled value

### ISSUE THREAD

**Issue by a-type** [chakra-ui/chakra-ui#2650]
# Bug report

## Describe the bug

When using NumberInput as an uncontrolled / ref-controlled field (i.e. interacting with the `ref` to set and get the value), the steppers do not respect the value of the input and instead behave as if it always begins at `0`.

Common use case for this: usage with `react-hook-form`, which utilizes refs and direct value access instead of `value / onChange` to set and get the field value.

## To reproduce

https://codesandbox.io/s/serene-morse-gf7mj?file=/src/App.js

Try using the increment or decrement stepper. Incrementing will set the value back to `1` instead of the expected `13`.

Clicking the input while it is `12` (default value) will also clear it, instead of editing `12`, as expected.

## Expected behavior

When I manipulate the `value` attribute of the underlying `input` utilizing a `ref`, at any time in or out of the React render loop:

1. The stepper controls should respond to the current input value when clicked
2. Focusing the input should retain the current value and allow me to increment with the scrollwheel or arrows starting at the current position.

## System information

- OS: macOs (Big Sur)
- Browser (if applies): Chrome, latest
- Version of @chakra-ui/react: 1.0.1
- Version of Node.js: any (probably 12 in CSB)

## Additional context

I'm new to Chakra but have a lot of experience with MUI. I like your approach so far! I'd be happy to look into fixing this behavior if I can find some time.

**Comment by jvmazagao** [comment]
@a-type Hello, looking at your code, you're using ref to manipulate the value of the Input, but, looking at the props of the component, if you want to add 1 by 1 using arrows, you need to pass default values to the props. Like this example

```
<NumberInput defaultValue={15} max={30} >
  <NumberInputField />
  <NumberInputStepper>
    <NumberIncrementStepper />
    <NumberDecrementStepper />
  </NumberInputStepper>
</NumberInput>
```

If I understand your question, the prop that you need to use is defaultValue, in the NumberInput component

**Comment by Samic8** [comment]
@with-heart Could you assign this one to me, please? If it passes triage.

I will be able to work on it next Monday/Tuesday. Thanks!

**Comment by segunadebayo** [comment]
I just pushed a fix for this @a-type. Thanks for catching it.

@Samic8 I sincerely appreciate the desire to help with this but I wanted to push the fix ASAP.

**Comment by Caleb-Hollingsworth** [comment]
This is still not fixed. Same thing with newest version. Please look into it.
