### ISSUE TITLE
[Button] href does not exist when used as anchor

### ISSUE THREAD

**Issue by divyanshu013** [chakra-ui/chakra-ui#346]
**Describe the bug**

I'm using typescript. When using the `Button` component with `as="a"` prop, it's throwing type error. My usage looks like:

```tsx
<Button as="a" href="http://localhost:4000/auth/github" leftIcon={FiGithub}>
  Login with GitHub
</Button>
```

The error being thrown is:
```
Type '{ children: string; as: "a"; href: string; leftIcon: IconType; }' is not assignable to type 'IntrinsicAttributes & IButton & Pick<PseudoBoxProps, "fontWeight" | "lineHeight" | "fontSize" | "letterSpacing" | "fontFamily" | ... 436 more ... | "_placeholder"> & { ...; }'.
 |   Property 'href' does not exist on type 'IntrinsicAttributes & IButton & Pick<PseudoBoxProps, "fontWeight" | "lineHeight" | "fontSize" | "letterSpacing" | "fontFamily" | ... 436 more ... | "_placeholder"> & { ...; }'.
```

I suspect this might be an issue with [type definitions](https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/Button/index.d.ts) of `Button` where it would need to support props of `a` if the component is being rendered as an anchor tag.

**Expected Behavior**

The error should not happen when `as="a"` is passed but it is valid if the `Button` is being rendered as an actual `button`

**To Reproduce**
- [Codesandbox link](https://codesandbox.io/s/chakra-button-type-definition-issue-7r4lp)
- Steps:
1. Use a `Button` component in a TS file with the above usage (with `as="a"` and `href` prop)
2. Check TS errors

**Suggested solution(s)**

I think type definitions have to be updated for this. Not sure how they should be handled dynamically based on `as` prop at the moment.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox 71.0
 - Version 0.52.0

**Comment by aaronmcadam** [comment]
Try this approach: https://github.com/chakra-ui/chakra-ui/issues/247#issuecomment-555953880

**Comment by divyanshu013** [comment]
I think it's fine as a workaround (currently I'm using a `@ts-ignore` on the href) but I feel this workaround shouldn't be needed and included in chakra core itself.

**Comment by aaronmcadam** [comment]
@divyanshu013 This is a well documented issue that's come up a lot. Here's an issue were myself and @segunadebayo discussed some possible solutions: https://github.com/chakra-ui/chakra-ui/issues/148.

@segunadebayo did we go with the solution using generics to pass the extra type or did you try using `infer`?

**Comment by divyanshu013** [comment]
Perhaps it can be added in docs as a small note just in case others run into same issue.

**Comment by aaronmcadam** [comment]
We were going to add a Recipes section to docs. I think that'd be a good place to show how to handle this issue.

**Comment by segunadebayo** [comment]
HI @divyanshu013, this has been resolved in the current TypeScript version we're working on. I'll add this to #205 for safe-keeping and double-checking.

**Comment by corysimmons** [comment]
>Posting this here because it's the first result for `linkbutton chakra`.

For NextJS users, I use this and it seems to work as expected:

```tsx
import Link, { LinkProps } from 'next/link'
import { Button, ButtonProps } from '@chakra-ui/react'

type Props = ButtonProps & LinkProps;

const LinkButton = ({ href, children, ...props }: Props) => (
	<Link href={href}>
		<Button as="a" cursor="pointer" {...props}>{children}</Button>
	</Link>
)

export default LinkButton
```

**Comment by floroz** [comment]
I am considering the adoption of Chakra UI for a new project within my company, it seems quite strange this TS issue is still unresolved?
