### ISSUE TITLE
EnvironmentProvider breaks SSR for Next.js

### ISSUE THREAD

**Issue by jacksonhardaker** [chakra-ui/chakra-ui#3844]
# 🐛 Bug report

After upgrading from `@chakra-ui/react@1.5.0` to `@chakra-ui/react@1.5.1`, the server side render in Next.js results in a single `<span></span>`.

Likely point of introduction: https://github.com/chakra-ui/chakra-ui/commit/81a40231f12461dcca0fa0cd3c4e9e2c0497a04d

## 💥 Steps to reproduce

1. Go to https://lyhzc.sse.codesandbox.io/
2. Open dev tools and disable JS
3. Refresh the page
4. Observe that the DOM contains `<div id="__next"><span></span></div>`

Alternatively

1. http https://lyhzc.sse.codesandbox.io/ | tidy -xml
2. Observe the same error

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/infallible-bardeen-lyhzc?file=/pages/_app.js

## 🧐 Expected behavior

Server render should return the expected html content.

## 🧭 Possible Solution

Only just starting to dig into this, but it looks like the [default environment](https://github.com/chakra-ui/chakra-ui/blob/87e66b897055a76ac50b3d62123c8140016196cb/packages/env/src/env.tsx#L16) needs to be more sophisticated can relying on `canUseDOM()`.

Interestingly, providing any old string as the `environment` seems to prevent the issue from occurring i.e.

```js
<ChakraProvider environment="...">
  <MyApp />
</ChakraProvider>
```

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      1.5.1      |
| Browser          |     Chrome 89.0.4389.128       |
| Operating System |       macOS 10.15.6     |

**Comment by jacksonhardaker** [comment]
On further inspection, it looks like this may have been fixed in https://github.com/chakra-ui/chakra-ui/commit/428b65034f9b1dd42b7378d5d1fa941137952300

**Comment by segunadebayo** [comment]
This has been fixed and we're releasing an update shortly

**Comment by jesster2k10** [comment]
Hey, I'm still getting this issue, although using Vite & [vite-plugin-ssr](https://vite-plugin-ssr.com)
Working with `@chakra-ui/react@1.6.5`.

I'll try get a reproducible sandbox ready in a moment

```
react_devtools_backend.js:2574 Warning: Did not expect server HTML to contain a <div> in <div>.
    at span
    at EnvironmentProvider (http://localhost:8000/node_modules/.vite/@chakra-ui_react.js?v=f093bc58:7550:5)
    at ColorModeProvider (http://localhost:8000/node_modules/.vite/@chakra-ui_react.js?v=f093bc58:1891:5)
    at ThemeProvider2 (http://localhost:8000/node_modules/.vite/chunk-SJ27NAT5.js?v=f093bc58:418:43)
    at ThemeProvider2 (http://localhost:8000/node_modules/.vite/@chakra-ui_react.js?v=f093bc58:3518:5)
    at http://localhost:8000/node_modules/.vite/@chakra-ui_react.js?v=f093bc58:980:5
    at ChakraProvider (http://localhost:8000/node_modules/.vite/@chakra-ui_react.js?v=f093bc58:7583:5)
    at CookiesProvider2 (http://localhost:8000/node_modules/.vite/react-cookie.js?v=f093bc58:50:24)
    at App (http://localhost:8000/src/shared/app.tsx:29:3)
    at Page
    at Router2 (http://localhost:8000/node_modules/.vite/react-router-dom.js?v=f093bc58:1277:30)
 ```

**Comment by JClackett** [comment]
Also just getting this now: 

```
Warning: Did not expect server HTML to contain a <div> in <div>. span EnvironmentProvider@webpack-internal:///../../node_modules/@chakra-ui/react-env/dist/esm/env.js:36:7 ColorModeProvider@webpack-internal:///../..
```

Will try and get a repro too

**Comment by jesster2k10** [comment]
Manually providing the `environment` prop to `<ChakraProvider />` seems to have solved it for me, the reason being the `  const showEnvGetter = !node && !environmentProp` being set to true for some reason. So passing the prop set it to false, causing the `<span></span>` not to render and the SSR client to hydrate properly.

I just copied out the `mockWindow` and `mockClient` from the `react-env` package and included them like so:
```
<ChakraProvider
            theme={theme}
            colorModeManager={cookieStorageManager(cookies)}
            environment={
              typeof window === 'undefined'
                ? {
                    document: ssrDocument,
                    window: ssrWindow,
                  }
                : {
                    window,
                    document,
                  }
            }
          >
</ChakraProvider>
```

Not sure why this is happening, seems to only be triggered when I render either a `<Route />` or `React.Context` component within the provider.
