### ISSUE TITLE
Chakra-UI + NextJS - useBreakpointValue not working with NextJS!

### ISSUE THREAD

**Issue by LuizHonorato** [chakra-ui/chakra-ui#5506]
### Description

 When I use the useBreakpointValue hook inside a component using NextJS, the application breaks and I get the error: Warning: Did not expect server HTML to contain a div in div.

### Link to Reproduction

https://codesandbox.io/s/keen-chaplygin-n7zcw

### Steps to reproduce

1. Go to https://codesandbox.io/s/keen-chaplygin-n7zcw
2. Wait for the application to load and see the console

### Chakra UI Version

@chakra-ui/core = 0.8.0 / @chakra-ui/react = 1.8.1 

### Browser

Google Chrome 97.0.4692.99

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

@chakra-ui/react: latest (1.8.1)
@emotion/react: latest (11.7.1)
@emotion/styled: latest (11.6.0)
@types/node: 17.0.12
@types/react: 17.0.38
framer-motion: latest (6.2.3)
next: 12.0.9
react: 17.0.2
react-dom: 17.0.2
typescript: 4.5.5

![image](https://user-images.githubusercontent.com/27831080/152046536-dd85b7f5-075b-4d02-9643-1f310fe6bab6.png)

**Comment by with-heart** [comment]
I can verify a similar issue on `1.8.1`. I believe I tried the same thing on `1.8.0` recently and didn't have this issue, so I think we have a regression.

Will try to find time to dig into it a little more later to verify

**Comment by rafaellupo** [comment]
Happens here too. Only in DEV env despite everything still working as expected.

**Comment by vdhpieter** [comment]
I have a similar issue, but my layout is screwed and it's happing since the `framer-motion` update. If I revert that one to `5.6.0` everything works as expected

**Comment by hazim-j** [comment]
Have similar issues. Had to revert `@chakra-ui/react` to `1.7.3`.

**Comment by csandman** [comment]
Having the same issue, but only when statically generating components which include `useBreakpointValue`. If I use a next.js `dyamic` import, then this functions fine.

It would make sense if the initial value could not be pulled because the screen size can't be accessed, but the main problem is that the value is not being updated after the page loads.

**Comment by indiana-dev** [comment]
Same issue here, as it was my first time using NextJS I spent several days thinking I was using Next wrong... did not suspect Chakra. Reverting to `1.7.3` as @hazim-j suggested fixed it for me too.

**Comment by DomVinyard** [comment]
Isn't solved for me in version 1.7.3 or 1.8.0. It's only on initial page load - if I navigate within the app everything is defined correctly, but when I reload the browser the values are not being applied

**Comment by TimKolberger** [comment]
We recently merged a PR which could fix this. Kindly check if this is fixed in this dev release: `@chakra-ui/react@0.0.0-dev-2022117203714`

We will cut a new release in the next few days.

**Comment by TimKolberger** [comment]
The fix is now released in @chakra-ui/react@1.8.5

**Comment by vdhpieter** [comment]
Works for me now!

**Comment by TimKolberger** [comment]
> @TimKolberger still an issue in this context https://github.com/cschroeter/chakra-ui-bug-ssr-breakpoint

I just pushed a PR for this. Kindly let me know if it fixes your issue or if you see any points to improve this.

**Comment by marcuslamounier** [comment]
Hello, @TimKolberger , I still have the same problem in version 1.8.5. I also downgraded to version 1.7.3.

**Comment by cyberwombat** [comment]
@TimKolberger was this pushed to V2 as well? I just upgraded to fix the toastprovider issue with react 18 and now getting this error.

**Comment by cyberwombat** [comment]
I am on "2.0.0-next.4"  and experiencing same issue with this code `const isDesktop = useBreakpointValue({ base: false, lg: true })`.

**Comment by nathansportfolio** [comment]
March 2023, still getting this issue on `"@chakra-ui/react": "^2.4.1",`

**Comment by SugarDarius** [comment]
Hello 👋🏻 
I'm experiencing also this issue on `"@chakra-ui/react": "2.6.0"`.  Thanks!

**Comment by moconnell** [comment]
Hello, co-sign also with `"@chakra-ui/react": "^2.8.0"`

**Comment by aJV99** [comment]
Hello. Any update? Still getting this error?

**Comment by kaue-delmonte** [comment]
I was facing the same issue, then I read the [documentation](https://chakra-ui.com/docs/hooks/use-breakpoint-value) and found this:

```jsx
const buttonSize = useBreakpointValue({ base: 'sm', lg: 'md' }, { ssr: false })

const breakpoint = useBreakpoint({ ssr: false })
```

Adding `ssr: false` worked for me and resolved all errors.

**Comment by DungGramer** [comment]
I see it in docs:
For SSR, you can use a package like [is-mobile](https://github.com/kaimallea/isMobile) to get the default breakpoint value from the user-agent
