### ISSUE TITLE
Semantic tokens don't work with DarkMode and LightMode component

### ISSUE THREAD

**Issue by lcswillems** [chakra-ui/chakra-ui#5526]
### Description

Semantic tokens don't work with DarkMode component.

### Link to Reproduction

https://codesandbox.io/s/intelligent-thompson-563p3?file=/src/index.tsx

### Steps to reproduce

This code is not working:

```
const App = () => (
  <ChakraProvider
    theme={extendTheme({
      semanticTokens: {
        colors: {
          text: {
            default: "red.700",
            _dark: "red.200"
          }
        }
      }
    })}
  >
    <DarkMode>
      <GlobalStyle />
      <Heading color="text">Welcome to Chakra + TS</Heading>
    </DarkMode>
  </ChakraProvider>
);
```

1. Go to 'https://codesandbox.io/s/intelligent-thompson-563p3?file=/src/index.tsx'
2. Heading should be in light red.

### Chakra UI Version

1.8.1

### Operating System

- [ ] macOS
- [ ] Windows
- [x] Linux

**Comment by with-heart** [comment]
Thanks for the bug report and reproduction!

**Comment by TimKolberger** [comment]
This is currently a documented edge case.

> The CSS variables are attached to the host element (CSS selector :host, :root) and cannot react to the components `<LightMode />` and `<DarkMode />`, `data-theme` attributes nor body class `.chakra-ui-dark`. It listens to e.g. html[data-theme="dark"]. - [Docs](https://chakra-ui.com/docs/features/semantic-tokens)

We are working on a feature to re-attach the css vars to an element to create a new token layer - this would enable the semantic tokens to react to `data-theme` attributes.

**Comment by lcswillems** [comment]
You're right I missed it in the doc!

**Comment by with-heart** [comment]
> You're right I missed it in the doc!

Same here 😰 Thanks @TimKolberger!

**Comment by segunadebayo** [comment]
Fixed in https://github.com/chakra-ui/chakra-ui/pull/5532 and will be release shortly

**Comment by lcswillems** [comment]
Great!!

**Comment by lcswillems** [comment]
@segunadebayo Has it been released? I have upgraded the codesandbox I shared in my first message and it is still not working

**Comment by TimKolberger** [comment]
It was released with a slight twist.


The css variables need a DOM Element to attach them again.
The LightMode and DarkMode components do not render an Element, they render only a React Context Provider.
Rendering the Element inside of DarkMode would be a breaking change and would introduce a circular dependency.

This code example shows how to use the _dark values of your Semantic Tokens.

```jsx
<DarkMode>
  <div data-theme="dark">
    <chakra.div color="your-semantic-token">
      This uses always the _dark value of your semantic token
    </chakra.div>
  </div>
</DarkMode>
```

We know that this API is not the most intuitive, and we will revisit this API in the future.

**Comment by lcswillems** [comment]
Thanks for the help!
