### ISSUE TITLE
Warning: ReactDOM.render is no longer supported in React 18.

### ISSUE THREAD

**Issue by performautodev** [chakra-ui/chakra-ui#5795]
### Description

Warning: ReactDOM.render is no longer supported in React 18.

### Link to Reproduction

https://github.com/performautodev/my-app

### Steps to reproduce

Created with 

```
npx create-next-app@latest --ts

```
=> no errors

Add chakra

```
yarn add @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^6

```

=> when i added ChakraProvider error appear :o

next-dev.js?3515:25 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

look at "./2022-03-30_13-42-43.png"

https://github.com/performautodev/my-app

### Chakra UI Version

1.8.7

### Browser

Version 99.0.4844.82 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Operating System:        
  Platform: win32        
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 16.14.2
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant packages:       
  next: 12.1.3-canary.0  
  react: 18.0.0
  react-dom: 18.0.0    

=> NextJS post : https://github.com/vercel/next.js/issues/35723

**Comment by balazsorban44** [comment]
I think this is because Chakra UI's Toast component is explicitly using `render` from `react-dom`: https://github.com/chakra-ui/chakra-ui/blob/7fc8742394fcd2de80d5b17e8325b148b1ed37b7/packages/toast/src/toast.class.tsx#L3

The allowed peer dependency version should either be updated, or the `render` function should be called conditionally: https://github.com/chakra-ui/chakra-ui/blob/7fc8742394fcd2de80d5b17e8325b148b1ed37b7/packages/toast/package.json#L54

**Comment by gaearon** [comment]
The recommendation is to use a Portal. It is not recommended to have multiple roots for things like toasts etc.

**Comment by performautodev** [comment]
Clear, thanks' man note that in my-app I don't use toasts just a simple nextjs-chakra-ui project contain "test" text :)
maybe they have to use createRoot instead of "ReactDOM.render"
@segunadebayo your opinion ?

**Comment by TimKolberger** [comment]
@performautodev The current toast implementation creates a second React root as soon as the code (mentioned by @balazsorban44) is loaded. Because of this we see this error even without using a toast.

I think we should fix this in two iterations:
1. create a fix to use `React.createRoot` (React >= v18) and fallback to `React.render` (React < v18)
2. update the toast package to use a Portal implementation

**Comment by GreatestOfAllTimee** [comment]
do we have a any update for this?

**Comment by TimKolberger** [comment]
It won't be possible to support React 18 without a breaking change to `createStandaloneToast`.

We will update the toast package to use a Portal implementation, this will take a few days.

**Comment by alexburner** [comment]
@TimKolberger I see your fix made it in a couple days ago (thank you!) 

But the `@chakra-ui/react` package version hasn't changed:
```json
  "version": "1.8.7",
```
https://github.com/chakra-ui/chakra-ui/blame/main/packages/react/package.json#L3

When will your fix be available for use?

**Comment by maxcww** [comment]
Also got another issue. 

In React 18 we should replace the render function with createRoot according to https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis

This will break the `<ColorModeScript initialColorMode={theme.config.initialColorMode}/>`. 
You can test this by switching to dark mode, then refresh the page, and it becomes light again.

**Comment by daniellaera** [comment]
I don't think is linked directly to whatever component we use, toast or not...
Just when we inject `<ChakraProvider>` in the `_app.tsx` the warning appears.
any idea for this?

**Comment by TimKolberger** [comment]
We just released the first pre-release version of chakra-ui/react with the `next` tag. E.g. `chakra-ui/react@2.0.0-next.0`.

This release has a breaking change for the `createStandaloneToast` package (not `useToast`).

Please note that this version is not intended to be used in production!

If you are feeling adventurous, kindly test your app with that version and let us know any issues you may experience.

When we are confident that everything works as expected with React 18 we will release it with `chakra-ui/react@2.0.0`.

**Comment by performautodev** [comment]
After update all packages the Warring still exist : 
https://github.com/performautodev/my-app/tree/update-1

**Comment by verekia** [comment]
I can confirm that the toast-related warning is gone with `"@chakra-ui/react": "2.0.0-next.0"`.
Not sure about `ColorModeScript` though.

**Comment by TimKolberger** [comment]
@performautodev that was fast 🚀

In the package.json from the linked repo I don't see the `next` version of chakra-ui/react.
Using `chakra-ui/react@2.0.0-next.0` should remove that warning.

Known issues:
- calling `toast()` from `useToast()` will trigger the warning again due an upstream issue in reach-ui/toast

**Comment by daniellaera** [comment]
just to point out as well that with the version `@chakra-ui/react": "2.0.0-next.0` the `npm run build` fails
![chakra_error](https://user-images.githubusercontent.com/8995710/162485198-820f867d-dfba-4f8b-a3db-7eb2188f9b68.png)

**Comment by TimKolberger** [comment]
Kindly create new issues for each finding, which we can tackle one after another 😊

**Comment by gaearon** [comment]
I don’t understand the new API. Left a question here: https://github.com/chakra-ui/chakra-ui/pull/5797#issuecomment-1093995470

**Comment by daniellaera** [comment]
I have to be honest: at the moment I'm switching to antd, it seems to have a better integration with React v18, sorry

**Comment by gaearon** [comment]
@daniellaera Comments like this are not helpful. They're creating undue pressure on maintainers literally several days after the release. It's also the weekend.

**Comment by stephyswe** [comment]
Can PEOPLE please have patience? The devs of Chakra is aware of the situation. They will assert it but yelling constantly day after day isn't solving anything. 

Give them all time.

**Comment by medmin** [comment]
> I have to be honest: at the moment I'm switching to antd, it seems to have a better integration with React v18, sorry

antd is sh*t. If you want another ambush like the Christmas bomb, go ahead. Not to mention antd is driven by Alibaba's toxic open source culture. 

Good luck, mate.

**Comment by LoganAtCrypto** [comment]
After update to "@chakra-ui/react": "2.0.0-next.0", the warning gone.

**Comment by Henex1** [comment]
I having the same issue with next js

**Comment by Moanrisy** [comment]
> After updated to "@chakra-ui/react": "2.0.0-next.0", the warning gone.

How to update to 2.0.0 version?
when I use npm i @chakra-ui/react
i got 1.8.8 version

**Comment by performautodev** [comment]
@[Moanrisy](https://github.com/Moanrisy) 
on package.json replace this :

 "@chakra-ui/react": "2.0.0-next.0"

**Comment by performautodev** [comment]
I confirm that the issue has been fixed : 
Thank's to Chakra UI Team ❤❤❤

[TimKolberger](https://github.com/TimKolberger)

**Comment by GreatestOfAllTimee** [comment]
> "@chakra-ui/react": "2.0.0-next.0"

`2.0.0-next` only for Next.js or?

**Comment by ayuhito** [comment]
> > "@chakra-ui/react": "2.0.0-next.0"
> 
> 
> 
> `2.0.0-next` only for Next.js or?

It's to denote a pre-release version. Refer to the [Semver docs](https://semver.org/#spec-item-9) to learn more.

**Comment by GreatestOfAllTimee** [comment]
> > `2.0.0-next` only for Next.js or?
> 
> It's to denote a pre-release version. Refer to the [Semver docs](https://semver.org/#spec-item-9) to learn more.

got it, I thought it was for next.js only

**Comment by vasudeveloper001** [comment]
> 

If you are switching to different UI design system, then it's not an issue which is serious as no one switches to different design system in any production code that quickly.

**Comment by JakeSchroeder** [comment]
> just to point out as well that with the version `@chakra-ui/react": "2.0.0-next.0` the `npm run build` fails ![chakra_error](https://user-images.githubusercontent.com/8995710/162485198-820f867d-dfba-4f8b-a3db-7eb2188f9b68.png)

any update on this?

**Comment by jwandekoken** [comment]
`"@chakra-ui/react": "2.0.0-next.0"`, worked for me. Thanks to the team!

**Comment by MarcelWaldvogel** [comment]
@CaliforniaMountainSnake Yes, that is what has been described in this thread. Upgrade your `@chakra-ui/react` package to `2.0.0-next.0` (or newer, right now, `.4` is latest).

**Comment by GreatestOfAllTimee** [comment]
> @CaliforniaMountainSnake Yes, that is what has been described in this thread. Upgrade your `@chakra-ui/react` package to `2.0.0-next.0` (or newer, right now, `.4` is latest).

This also work on `create-react-app` or only for `Next.js`?

**Comment by verekia** [comment]
"-next" is not about Next.js, it's about the "next" version of Chakra. There are comments about this just above in this thread.

**Comment by CaliforniaMountainSnake** [comment]
@MarcelWaldvogel, there are errors when I try to use `2.0.0-next.0` version of `@chakra-ui/react`:
```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-focus-lock@2.5.2
npm WARN Found: react@18.1.0
npm WARN node_modules/react
npm WARN   react@"^18.0.0" from the root project
npm WARN   55 more (@chakra-ui/react, @emotion/react, @emotion/styled, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0" from react-focus-lock@2.5.2
npm WARN node_modules/react-focus-lock
npm WARN   react-focus-lock@"2.5.2" from @chakra-ui/focus-lock@2.0.0-next.2
npm WARN   node_modules/@chakra-ui/focus-lock
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0" from react-focus-lock@2.5.2
npm WARN   node_modules/react-focus-lock
npm WARN     react-focus-lock@"2.5.2" from @chakra-ui/focus-lock@2.0.0-next.2
npm WARN     node_modules/@chakra-ui/focus-lock
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-remove-scroll@2.4.1
npm WARN Found: react@18.1.0
npm WARN node_modules/react
npm WARN   react@"^18.0.0" from the root project
npm WARN   55 more (@chakra-ui/react, @emotion/react, @emotion/styled, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0" from react-remove-scroll@2.4.1
npm WARN node_modules/@chakra-ui/modal/node_modules/react-remove-scroll
npm WARN   react-remove-scroll@"2.4.1" from @chakra-ui/modal@2.0.0-next.3
npm WARN   node_modules/@chakra-ui/modal
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0" from react-remove-scroll@2.4.1
npm WARN   node_modules/@chakra-ui/modal/node_modules/react-remove-scroll
npm WARN     react-remove-scroll@"2.4.1" from @chakra-ui/modal@2.0.0-next.3
npm WARN     node_modules/@chakra-ui/modal

```
