### ISSUE TITLE
TypeScript Issue with NextJs 12 TypeError: utils.toMediaQueryString is not a function

### ISSUE THREAD

**Issue by henrychea** [chakra-ui/chakra-ui#6102]
### Description

Issue when running development mode causing a bug called TypeError: utils.toMediaQueryString is not a function

### Link to Reproduction

None

### Steps to reproduce

1. run `yarn dev`
2. Open localhost

### Chakra UI Version

2.0.1

### Browser

Google Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Attached logs

```
Server Error
TypeError: utils.toMediaQueryString is not a function

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
_loop
file:///Users/henrychea/Developer/app/app-web-application/node_modules/@chakra-ui/styled-system/dist/chakra-ui-styled-system.cjs.dev.js (2100:25)
resolver
file:///Users/henrychea/Developer/app/app-web-application/node_modules/@chakra-ui/styled-system/dist/chakra-ui-styled-system.cjs.dev.js (2124:18)
<unknown>
file:///Users/henrychea/Developer/app/app-web-application/node_modules/@chakra-ui/styled-system/dist/chakra-ui-styled-system.cjs.dev.js (2141:127)
useStyleConfigImpl
file:///Users/henrychea/Developer/app/app-web-application/node_modules/@chakra-ui/system/dist/chakra-ui-system.cjs.dev.js (366:18)
Object.useStyleConfig
file:///Users/henrychea/Developer/app/app-web-application/node_modules/@chakra-ui/system/dist/chakra-ui-system.cjs.dev.js (382:10)
<unknown>
file:///Users/henrychea/Developer/app/app-web-application/node_modules/@chakra-ui/button/dist/chakra-ui-button.cjs.dev.js (217:23)
renderWithHooks
file:///Users/henrychea/Developer/app/app-web-application/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5448:16)
renderForwardRef
file:///Users/henrychea/Developer/app/app-web-application/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5632:18)
renderElement
file:///Users/henrychea/Developer/app/app-web-application/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5795:11)
renderNodeDestructive
file:///Users/henrychea/Developer/app/app-web-application/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5875:11)
```

**Comment by henrychea** [comment]
I fixed it. Turns out @charka-ui/react and its peer dependencies aren't versioned correctly. 

If I do `npm i @chakra-ui/react` I will get errors for many of the peer dependencies because NPM will install `@chakra/react@2.0.1` which is versioned wrong from the peer dependencies (In my case it was `@chakra-ui/alerts`, which only had `@chakra-ui/alerts@2.0.0` as its latest version, causing NPM to error and not install). 

So just delete your node_modules folder, package-lock.json or yarn-lock.json and any `chakra-ui` package entries in your package.json. Then run `npm i @chakra-ui/react@2.0.0` or if you use yarn do the equivalent.

Then it all works now.

**Comment by isaachinman** [comment]
I don't think this issue should be closed. I am still unable to resolve things with `yarn`, and I can reproduce this in an empty directory.

Doing `yarn install @chakra-ui/react@2.0.0` leads to a bunch of `Couldn't find any versions for "@chakra-ui/utils"` errors.

@segunadebayo Can you please help to resolve these peer dependency issues?

**Comment by creotip** [comment]
Same problem here
![Uploading Screen Shot 2022-05-25 at 13.33.01.png…]()

**Comment by skreutzberger** [comment]
Yep, I have the same issue with `yarn`and can not resolve it in the way it could be resolved via `npm`.

**Comment by segunadebayo** [comment]
I'm not sure what the cause of this might be but we're releasing a new version of all packages as a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
