### ISSUE TITLE
 Chakra UI doesn't work with ESM

### ISSUE THREAD

**Issue by BeanWei** [chakra-ui/chakra-ui#6942]
### Description

Copy from https://github.com/chakra-ui/chakra-ui/issues/6661#issuecomment-1271072774 , I faced same issue.

Here is an example involving Vite (and thus Astro): https://stackblitz.com/edit/vitejs-vite-xfwglb?file=vite.config.ts

After running npm run build, starting the server with node dist/main.js will fail.

The reason is Chakra UI doesn't work with ESM yet. The following code is an example:

```js
// package.json
{
  "type": "module",
  "dependencies": {
    "@chakra-ui/react": "2.3.5"
  }
}
// index.js
import { Button } from '@chakra-ui/react';
// output
file:///home/projects/vitejs-vite-xfwglb/module-test/index.js:1
import { Button } from '@chakra-ui/react';
         ^^^^^^
SyntaxError: Named export 'Button' not found. The requested module '@chakra-ui/react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@chakra-ui/react';
const { Button } = pkg;

    at _instantiate (https://vitejs-vite-xfwglb.w-corp.staticblitz.com/blitz.c3f3eab0760382367e86f2a862c18516376c36f4.js:6:986717)
    at <anonymous> (<anonymous>)
```
The root cause is mentioned in this comment: https://github.com/chakra-ui/chakra-ui/issues/6783#issuecomment-1267496257. By renaming all esm.js to esm.mjs, I managed to get the code to run.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-xfwglb?file=vite.config.ts

### Chakra UI Version

2.3.5 & 2.3.7

### Browser

Edge latest version

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by ayoubqrt** [comment]
I'm facing the same problem here by using the vite-plugin-ssr.
Initialized my repo with `pnpm create vite-plugin-ssr@latest` https://github.com/ayoubqrt/vite-ssg

**Comment by nitedani** [comment]
Related: https://github.com/vitejs/vite/issues/11299
https://publint.bjornlu.com/@chakra-ui/react@2.4.3

**Comment by arthurgailes** [comment]
It seems that Chakra is not compatible with Vite 4, see the vite issue above. Reverting to Vite 3 should fix this issue.

**Comment by DarrenBaldwin07** [comment]
I am still getting a similar error here in version 2.4.5: ››
![Screen Shot 2022-12-28 at 9 57 57 AM](https://user-images.githubusercontent.com/68653294/209830933-81a00ab0-cc48-4ad8-a665-66abb3e0e527.png)

**Comment by morrisallison** [comment]
> I am still getting a similar error here in version 2.4.5: ›› ![Screen Shot 2022-12-28 at 9 57 57 AM](https://user-images.githubusercontent.com/68653294/209830933-81a00ab0-cc48-4ad8-a665-66abb3e0e527.png)

My experience is the same, but the Chakra UI packages themselves seem to be fine now, it's their dependencies that are the issue now.

A number of Chakra UI's dependencies aren't Node ESM friendly; it's a rabbit hole of patches. However, those issues should probably be taken up with each respective package author.

Regardless, I agree the outcome is the same though.
