### ISSUE TITLE
Issue with NextJS 13 - ESM Modules

### ISSUE THREAD

**Issue by zmalatrax** [chakra-ui/chakra-ui#7167]
### Description

When I setup a NextJS 13 typescript project and install chakra-ui, and add <ChakraProvider> tag, the next server crash and returns an ESM related error: 
```
Server Error

SyntaxError: Named export 'cancelSync' not found. The requested module 'framesync' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'framesync';
const { cancelSync, getFrameData } = pkg;
This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

### Link to Reproduction

https://codesandbox.io/p/sandbox/nifty-hill-uoc5q2

### Steps to reproduce

1. Setup a NextJS project: `yarn create next-app --typescript`
2. Add chakra-ui:  `yarn add @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^6`
3. Add ChakraProvider tags to _app.jsx
```Typescript
import type { AppProps } from "next/app";
import { ChakraProvider } from "@chakra-ui/react";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <ChakraProvider>
      <Component {...pageProps} />
    </ChakraProvider>
  );
}
``` 

### Chakra UI Version

^2.4.5

### Browser

Mozilla Firefox 108.0.1 (64 Bits) & Brave 1.46.144

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

I found a few somehow related issues concerning Chakra UI & ESM clashes, such as #6942 but I didn't manage to fix this issue.
The codesandbox was made with the nextJS template provided, it uses npm but still has the same error.

My package.json:
```JSON
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@chakra-ui/react": "^2.4.5",
    "@emotion/react": "^11",
    "@emotion/styled": "^11",
    "@next/font": "13.1.1",
    "@types/node": "18.11.17",
    "@types/react": "18.0.26",
    "@types/react-dom": "18.0.10",
    "eslint": "8.30.0",
    "eslint-config-next": "13.1.1",
    "framer-motion": "^6",
    "next": "13.1.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "4.9.4"
  }
}
```

**Comment by bruno3du** [comment]
I check here and it is happening in next 12 as well

**Comment by oscar8x** [comment]
Yes, it was working fine 5 hours ago in Next 12.3.1 but it's failing right now

**Comment by oemilsson** [comment]
Looks like they have started using ES modules. Worked for me again by downgrading to 2.4.2.

**Comment by prabhjotsinghchadha** [comment]
I am also getting same issue..

**Comment by kgilliam125** [comment]
Confirmed this is not working for me either on Next 13.x. Redeployed my app from Vercel after changing env vars and received the same error. No code changes on my end.

**Comment by gmatthewsfeuer** [comment]
Same issue

![Screenshot_20221226-173500.png](https://user-images.githubusercontent.com/47375774/209581889-fe7da4c8-adaa-4402-8fef-53b258ca535f.png)

**Comment by kgilliam125** [comment]
@oemilsson Just changing chakra version didn't work for me on Vercel, had to update other chakra deps as well. Here is a working set of dependencies from my package.json

```
    "@chakra-ui/icons": "2.0.13",
    "@chakra-ui/react": "2.4.2",
    "@chakra-ui/theme-tools": "2.0.14",
```

Local builds seem fine with any version, so be aware.

**Comment by angelollima** [comment]
same error here

**Comment by wenotch** [comment]
Having same issue here

**Comment by be-ansh-sharma** [comment]
same error here. Work is blocked

**Comment by angelollima** [comment]
> > any one have a workaround for this?
> 
> Downgrade your package to exactly `2.4.2` instead of `^2.4.4`

Don't get me wrong... i'm a beginner. Downgrade my package... what next? Am i never gonna get one upgrade?

**Comment by angelollima** [comment]
> > > > any one have a workaround for this?
> > > 
> > > 
> > > Downgrade your package to exactly `2.4.2` instead of `^2.4.4`
> > 
> > Don't get me wrong... i'm a beginner. Downgrade my package... what next? Am i never gonna get an upgrade?
> 
> Change the version number in `package.json` to use the mentioned version until they patch this issue in a future release at which point you can update to that version.

When they fix the issue, i just new to change the version number ?? I thought i had to do some command on the terminal line, thank you so much

**Comment by danish17** [comment]
> 

You can simply re-run the command which you used to install Chakra UI, like `yarn add @chakra-ui/react`, it will update the version.

**Comment by danish17** [comment]
> > > > > any one have a workaround for this?
> > > > 
> > > > 
> > > > Downgrade your package to exactly `2.4.2` instead of `^2.4.4`
> > > 
> > > 
> > > Don't get me wrong... i'm a beginner. Downgrade my package... what next? Am i never gonna get an upgrade?
> > 
> > 
> > Change the version number in `package.json` to use the mentioned version until they patch this issue in a future release at which point you can update to that version.
> 
> When they fix the issue, i just new to change the version number ?? I thought i had to do some command on the terminal line, thank you so much

You can simply re-run the command which you used to install Chakra UI, like `yarn add @chakra-ui/react`, it will update the version.

**Comment by danish17** [comment]
> It appears that #6472 broke this by bumping the `framesync` package. It appears [other upstream packages are having issues](https://github.com/Popmotion/popmotion/issues/946) with the way they handle ESM modules as well. I don't contribute to `chakra-ui` but would love if someone else could patch this as I am running into the same issue as well.

Yes, other packages are having issues as well. Was trying to troubleshoot the issue but encountered another one with `@zag-js/focus-visible`.

**Comment by danish17** [comment]
> > > > > any one have a workaround for this?
> > > > 
> > > > 
> > > > Downgrade your package to exactly `2.4.2` instead of `^2.4.4`
> > > 
> > > 
> > > Don't get me wrong... i'm a beginner. Downgrade my package... what next? Am i never gonna get an upgrade?
> > 
> > 
> > Change the version number in `package.json` to use the mentioned version until they patch this issue in a future release at which point you can update to that version.
> 
> When they fix the issue, i just new to change the version number ?? I thought i had to do some command on the terminal line, thank you so much

You can simply run a command to upgrade the package. If you're on Yarn, you can run `yarn upgrade @chakra-ui/react@latest`.

**Comment by angelollima** [comment]
I just removed @chakra-ui/react, and installed again and it's working rn

**Comment by Johra444** [comment]
Does not work for me even after downgrading ...

**Comment by Lyons800** [comment]
Same here

**Comment by Johra444** [comment]
For those like me wich downgrading packaged.json does not work, try this (worked for me) 👍 

npm uninstall @chakra-ui/react

npm i @chakra-ui/react@2.4.2

npm run dev

**Comment by inhwangYang** [comment]
> 

this is work for me.
But not yet in yarn

**Comment by angelollima** [comment]
> For those like me wich downgrading packaged.json does not work, try this (worked for me) 👍 
> 
> npm uninstall @chakra-ui/react
> 
> npm i @chakra-ui/react@2.4.2
> 
> npm run dev
> 

Worked for me, thanks

**Comment by wenotch** [comment]
> 12.3.1

this worked

**Comment by parnexcodes** [comment]
> @oemilsson Just changing chakra version didn't work for me on Vercel, had to update other chakra deps as well. Here is a working set of dependencies from my package.json
> 
> ```
>     "@chakra-ui/icons": "2.0.13",
>     "@chakra-ui/react": "2.4.2",
>     "@chakra-ui/theme-tools": "2.0.14",
> ```
> 
> Local builds seem fine with any version, so be aware.

`"@chakra-ui/icons": "2.0.13"`
is still giving issues.

**Comment by bibakroy** [comment]
I faced this issue and solved it. Just changed the versions as it is below:

`yarn add @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1
`
You can try it. Will definitely work.

**Comment by jvandenaardweg** [comment]
Problem got introduced in 2.4.5, everything working fine in 2.4.4:

`yarn add @chakra-ui/react@2.4.4`

**Comment by meabed** [comment]
Add this to your next.config.js to turn of esm bundling - this should make it work fine for now.

```
  experimental: {
    esmExternals: false,
  }

```

**Comment by serzhan181** [comment]
> Add this to your next.config.js to turn of esm bundling - this should make it work fine for now.
> 
> ```
>   experimental: {
>     esmExternals: false,
>   }
> ```
> 
> The default value of this in nextjs is true: https://github.com/vercel/next.js/blob/canary/packages/next/server/config-shared.ts#L598
> 
> so you need to turn it off.

what consequences i have to face by turning this off?

**Comment by meabed** [comment]
> what consequences i have to face by turning this off?

@serzhan181 depends on ur codebase! try it and see. I have updated the commend with more info too.

**Comment by SCG82** [comment]
Updating either of these results in the issue mentioned:
```json
"@chakra-ui/icons": "^2.0.14"
"@chakra-ui/react": "^2.4.4"
```

**Comment by st3fus** [comment]
I managed to fix it partially, Upgraded to these versions:
```"@chakra-ui/icons": "2.0.13",
"@chakra-ui/react": "2.4.2",```

But I now have a new problem... Seems like the react table that's mixed with Chakra is failing, I dont know why. (It doesn't not fail locally, only on production)

Here's the screenshot of console:

![image](https://user-images.githubusercontent.com/112018215/209693089-49cf1e97-b950-4bd9-8543-7c21b8fc8ada.png)

I even tried with the latest version, still the same
```"@tanstack/react-table": "8.7.4"```

**Comment by shinebayar-g** [comment]
Yup this update broke my Next.js app as well. Latest working version is `2.4.4.`
```
 @chakra-ui/react     ^2.4.4  →     ^2.4.5
```

Pinning to previous version "@chakra-ui/react": "2.4.4", like this for now until it's fixed.

**Comment by st3fus** [comment]
> 

Tried with 2.4.4, still the same...

**Comment by David-Mateus** [comment]
Tried with 2.4.4, still the same

**Comment by gibify** [comment]
I had the same issue here.

**Comment by charlezs** [comment]
this worked! thanks so much :)

**Comment by DarrenBaldwin07** [comment]
I am still getting this error as well (tried with 2.4.4, 2.4.2, and latest 2.4.5) -- can confirm this is not just a next issue. I am also getting the same framesync error with vite: 
![Screen Shot 2022-12-28 at 10 25 02 AM](https://user-images.githubusercontent.com/68653294/209834266-972007ab-7de0-4306-b923-777eb920dfb7.png)

**Comment by sakho13** [comment]
I got this error.
Now, I saw this package.json is working.
`
"@chakra-ui/react": "^2.4.2",
"@emotion/react": "^11.10.5",
"@emotion/styled": "^11.10.5",
"framer-motion": "^8.0.2",
"next": "13.1.1",
`

**Comment by st3fus** [comment]
> I got this error. Now, I saw this package.json is working. `"@chakra-ui/react": "^2.4.2", "@emotion/react": "^11.10.5", "@emotion/styled": "^11.10.5", "framer-motion": "^8.0.2", "next": "13.1.1",`

Tried that as well, still not working

**Comment by fabriciosiqp** [comment]
This here worked for me:

1. Delete node_modules and yarn.lock or package-lock.json
2. Remove all package carets from package.json
3. run yarn install or npm install again

For me this happened after I moved my project to another computer. Which intrigued me a lot because I was sure it should work so I did it and it worked perfectly.

Anyway, I hope I helped

**Comment by yud0uhu** [comment]
In my environment, the error was resolved by updating the yarn version from 1 to 3.
I hope this helps.

**Comment by yuikoito** [comment]
> In my environment, the error was resolved by updating the yarn version from 1 to 3.

Still have problems in my environment...
yarn version is v3.0.0.

**Comment by yuikoito** [comment]
> Delete node_modules and yarn.lock or package-lock.json
Remove all package carets from package.json
run yarn install or npm install again

Tried all, but still doesn't work..

**Comment by yuikoito** [comment]
@meabed 

> Add this to your next.config.js to turn of esm bundling - this should make it work fine for now.
  experimental: {
    esmExternals: false,
  }

Finally it works! Thank you!

**Comment by conceptofmind** [comment]
> Add this to your next.config.js to turn of esm bundling - this should make it work fine for now.
> 
> ```
>   experimental: {
>     esmExternals: false,
>   }
> ```
> 
> The default value of this in nextjs is true: https://github.com/vercel/next.js/blob/canary/packages/next/server/config-shared.ts#L598
> 
> so you need to turn it off.
> 
> Turning off this will not affect your code most of the time unless you are using esm in your code ( which i think 99% of people don't )
> 
> To understand more: https://nextjs.org/blog/next-12#es-modules-support-and-url-imports

This worked for me. Just edited the config file and changed boolean value to false.

**Comment by segunadebayo** [comment]
Thanks for chiming in with an immediate workaround @meabed.

This issue happened due to our recent move to `.mjs` file extensions for better ESM detection. Some of our internal dependencies did not fully support ESM.

I've gone ahead to fix most of the ESM/CJS-related errors. I just published a new version.

If, after upgrading and the problem still exists in your application, I'll re-open it.

**Comment by calvo-jp** [comment]
> I faced this issue and solved it. Just changed the versions as it is below:
> 
> `yarn add @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1` or `npm install @chakra-ui/react@2.4.2 @emotion/react@^11.10.5 @emotion/styled@^11.10.5 framer-motion@^6.5.1`
> 
> You can try it. Will definitely work.

Thanks, bro. The problem is coming from chakra ui indeed. downgraded it to `2.4.2` and it works fine now.

**Comment by kamilsk** [comment]
could you provide more details? we use nextjs 13 and it works well with chakra. proofs

- https://github.com/tact-app/web/blob/ae0a54d28e8c314e5fb2a5b76e8eabd3db106077/package.json#L55
- https://github.com/tact-app/web/blob/ae0a54d28e8c314e5fb2a5b76e8eabd3db106077/package.json#L21-L24

**Comment by pip8786** [comment]
> Thanks for chiming in with an immediate workaround @meabed.
> 
> This issue happened due to our recent move to `.mjs` file extensions for better ESM detection. Some of our internal dependencies did not fully support ESM.
> 
> I've gone ahead to fix most of the ESM/CJS-related errors. I just published a new version.
> 
> If, after upgrading and the problem still exists in your application, I'll re-open it.

Are you saying this workaround is no longer needed?
```
  experimental: {
    esmExternals: false,
  }
```
I was still getting issues after upgrading everything to the latest today and had to add that to my next config.
