### ISSUE TITLE
TS2590: Expression produces a union type that is too complex to represent when on TS 5.0.2

### ISSUE THREAD

**Issue by capaj** [chakra-ui/chakra-ui#7459]
### Description

I just upgraded to TS 5.0 and I started getting:

```ts
src/pages-vault/Devices.tsx:104:15 - error TS2590: Expression produces a union type that is too complex to represent.

104               <MenuButton
                  ~~~~~~~~~~~
105                 as={IconButton}
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
110                 icon={<SettingsIcon color={'white'} />}
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
111               />
    ~~~~~~~~~~~~~~~~

```

```ts
src/AuthLinkPage.tsx:23:11 - error TS2590: Expression produces a union type that is too complex to represent.

23           <Heading size="sm">
             ~~~~~~~~~~~~~~~~~~~
24             <Trans>Open vault to login or sign up</Trans>
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
25           </Heading>
   ~~~~~~~~~~~~~~~~~~~~


```

in couple places in the codebase where I use  `Heading` or `Text` components

### Link to Reproduction

sorry no sandbox

### Steps to reproduce

no sandbox

### Chakra UI Version

2.5.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by ygorduraes** [comment]
Same. It might be lack of support for TS5, and apparently, it's also an old bug: https://github.com/chakra-ui/chakra-ui/issues/3714#issuecomment-1473286906

@salemhilal created a reproducible example here: [https://www.typescriptlang.org/play?ts=5.1.0-dev.20230316#code/JYWwDg9...](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230316#code/JYWwDg9gTgLgBAbzgYQgOxgQ2GgplOAXzgDMoIQ4ByAAQGMALTAaykwFoBXYAeil0x0YVANwAoMXXQBnePAC8cABQBKOPIB8cADyoM2PAR4aRQA) (from https://github.com/chakra-ui/chakra-ui/issues/3714#issuecomment-1473048404)

**Comment by salemhilal** [comment]
I would add that I was able to successfully avoid this problem by using React 17 types (I'm not suggesting that's a good fix), so I believe React 18's types are required to reproduce this bug.

**Comment by vboechat** [comment]
Same error here, but with `Container`.

**Comment by GabrieSpontoni** [comment]
same error here

**Comment by capaj** [comment]
It's not much, but I'll send 0.15 LTC to whoever fixes this.
Just post your wallet address in here or into the fix PR if you want to claim it.

**Comment by ShyAssassin** [comment]
Getting the same error with `Text` with Typescript@5.0.2 downgrading to Typescript@4.9.5 like @vboechat suggests fixed it for me

**Comment by xobotyi** [comment]
Same here. had to switch back to typescript@4.9.5

**Comment by hkvongit** [comment]
The same issue came in latest Next.js app created with `create-next-app` because next was using typescript 5.0.2. I had to downgrade typescript to version 4.9.5 and reinstall the npm packages.

**Comment by asborisov** [comment]
Same for me but on `Tabs` component. I assume there's some set of error-prone component and the first TS finds, breaks the compilation

**Comment by SferaDev** [comment]
Spent some time today with this one, with git bisect was able to narrow down to: https://github.com/microsoft/TypeScript/pull/51152 and `5.0.0-dev.20221118` as plausible first regression point.

Also tried reverting the change in `5.0.2` and seems to work just fine. I'll try to dive in a bit more to see if it's on TypeScript to fix it or Chakra's types can be simplified to avoid hitting the problem.

**Comment by yardenxr** [comment]
i have the same issue when trying to upgrade to ts 5.0.2.

**Comment by milliorn** [comment]
I am having this issue with Image
```tsx
import { Heading, Image, Text } from "@chakra-ui/react";
import logo from "../assets/light-bulb.svg";
import React from "react";

function Header(): JSX.Element {
  return (
    <>
      <Image src={logo} alt="logo" width={100} marginBottom="1rem" />
      <Heading color="white" marginBottom="1rem">
        Keyword Generator
      </Heading>
      <Text fontSize={25} textAlign="center">
        Paste in your text below.
      </Text>
    </>
  );
}

export default Header;
```

```
src/components/Header.tsx:8:7 - error TS2590: Expression produces a union type that is too complex to represent.

       <Image src={logo} alt="logo" width={100} marginBottom="1rem" />
```

**Comment by segunadebayo** [comment]
I looked into this yesterday and tweaked the typings to get it working and avoid hitting the complex union type issue.

@capaj, feel free to leave the bounty in the [Open Collective](https://opencollective.com/chakra-ui) 😉

I'll release an update shortly.

**Comment by mareksuscak** [comment]
Thank you so much @segunadebayo! What version has this been fixed in? Still seeing in Chakra 2.5.5 with Typescript 5.0.3.

**Comment by Averethel** [comment]
@mareksuscak you need to update `@chakra-ui/system` to 2.5.5 - that's where the underlying fixes are

**Comment by asborisov** [comment]
We have the latest version of everything: `@chakra-ui/react@2.5.5`, `@chakra-ui/system@2.5.5`, `@chakra-ui/accordion@2.1.11` and `typescript@5.0.3`
We also common wrappers like following:
```ts
import { AccordionButtonProps, AccordionButton as ChakraAccordionButton } from '@chakra-ui/react';

export const AccordionButton = ({ children, ...props }: AccordionButtonProps) => (
  <h3>
    <ChakraAccordionButton {...props}>{children}</ChakraAccordionButton>
  </h3>
);
```
Still getting the same exception: `TS2590: Expression produces a union type that is too complex to represent.`

**Comment by capaj** [comment]
I tried updating as well, everything latest and I got even more type errors than with 2.5.4 chakra.

**Comment by staevs** [comment]
> I'll release an update shortly.

Thanks a lot, after updating issue has gone. Can you, plz, share the underlying issue that caused the error (or point the commit that fixed it)?

**Comment by n1xx1** [comment]
> I tried updating as well, everything latest and I got even more type errors than with 2.5.4 chakra.

Same here. And going back to TS 4.9.5 while leaving @chakra/react 2.5.5, I now get the same errors aswell.

**Comment by mareksuscak** [comment]
> @mareksuscak you need to update `@chakra-ui/system` to 2.5.5 - that's where the underlying fixes are

I'm on 2.5.5 for this particular package, seeing the type error regardless. We should re-open this GH issue.

**Comment by bryanjswift** [comment]
I'm fairly sure this was closed prematurely. This minimal reproduction (also at https://gist.github.com/bryanjswift/3caee09992569aa385a15290842c3e92):

```ts
// index.tsx
import { Container } from '@chakra-ui/react';

const t = () => <Container />;
```

Still produces an error for me with this configuration.

```jsonc
// package.json
{
  "name": "chakra-7506-reproduction",
  "packageManager": "yarn@4.0.0-rc.42",
  "dependencies": {
    "@chakra-ui/icons": "^2.0.18",
    "@chakra-ui/react": "^2.5.5",
    "@chakra-ui/system": "^2.5.5",
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "framer-motion": "^10.10.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@tsconfig/node18": "^1.0.1",
    "@types/react": "^18.0.31",
    "@types/react-dom": "^18.0.11",
    "typescript": "^5.0.3"
  }
}
```

```jsonc
// tsconfig.json
{
  "extends": "@tsconfig/node18/tsconfig.json",
  "compilerOptions": {
    "composite": true,
    "declarationMap": true,
    "incremental": true,
    "lib": [
      "dom",
      "es2021"
    ],
    "jsx": "react-jsx",
    "jsxImportSource": "@emotion/react",
    "target": "es2018",
    "outDir": "dist/",
    "declaration": true,
    "emitDeclarationOnly": true,
    "isolatedModules": true
  },
  "include": [
    "src/**/*",
    "test/**/*"
  ],
  "exclude": [
    "node_modules"
  ],
  "references": [
  ]
}
```

**Comment by suleymanozkeskin** [comment]
I too have the same issue , TS version: 5.0.2 , Chakra-ui 2.5.3. I tried downgrading TS but got even more errors.

**Expression produces a union type that is too complex to represent.ts(2590)**

`

// src/components/ColorModeToggle.tsx
import React from 'react';
import { IconButton, useColorMode } from '@chakra-ui/react';
import { FaMoon, FaSun } from 'react-icons/fa';

const ColorModeToggle: React.FC = () => {
  const { colorMode, toggleColorMode } = useColorMode();

  const bgColor = { light: 'gray.300', dark: 'gray.600' };
  const hoverBgColor = { light: 'gray.400', dark: 'gray.500' };
  const activeBgColor = { light: 'gray.500', dark: 'gray.400' };

  return (
    <IconButton
      aria-label="Toggle color mode"
      icon={colorMode === 'light' ? <FaMoon /> as React.ReactElement : <FaSun /> as React.ReactElement}
      onClick={toggleColorMode}
      bgColor={bgColor[colorMode]}
      _hover={{
        bgColor: hoverBgColor[colorMode],
      }}
      _active={{
        bgColor: activeBgColor[colorMode],
      }}
      borderRadius="md"
    />
  );
};

export default ColorModeToggle;

`

**Comment by emrerdem1** [comment]
Why this was closed? It still occurs both on TS 4.9.5 and 5.0.2.

**Comment by bryanjswift** [comment]
> Why this was closed? It still occurs both on TS 4.9.5 and 5.0.2.

I opened https://github.com/chakra-ui/chakra-ui/issues/7526 because I don't think this should have been closed and I can still reproduce the issue.

**Comment by TimMensch** [comment]
@emrerdem1 @bryanjswift I was having the same problem, and I fixed it by bumping versions:

```
        "@chakra-ui/icons": "^2.0.18",
        "@chakra-ui/react": "^2.5.5",
        "@chakra-ui/system": "^2.5.5",
```

and

```
        "typescript": "^5.0.4",
```

With that set of updates, all of the instances of this warning that I was experiencing, plus all the examples given above (I just checked), have been fixed.

**Comment by mareksuscak** [comment]
> @emrerdem1 @bryanjswift I was having the same problem, and I fixed it by bumping versions:
> 
> ```
>         "@chakra-ui/icons": "^2.0.18",
>         "@chakra-ui/react": "^2.5.5",
>         "@chakra-ui/system": "^2.5.5",
> ```
> 
> and
> 
> ```
>         "typescript": "^5.0.4",
> ```
> 
> With that set of updates, all of the instances of this warning that I was experiencing, plus all the examples given above (I just checked), have been fixed.

I just tested this and it doesn't help. The error is still occuring. The only thing that currently helps is `typescript@4.9.5` and `@chakra-ui/react@2.5.4`.

**Comment by nerixim** [comment]
Works with Chakra 2.5.5 and Typescript 5.0.4
Any chance you have some dependencies with multiple versions installed? @mareksuscak

**Comment by mareksuscak** [comment]
![CleanShot 2023-04-15 at 23 09 57@2x](https://user-images.githubusercontent.com/613647/232253366-2af4bda2-e8fb-41db-ae24-0b8cdef96b83.png)

@nerixim doesn't seem to be the case.

**Comment by TimMensch** [comment]
@mareksuscak And what does `tsc --version` say?

Or what does it say when you run `yarn tsc`, which will run the version of tsc in package.json?

**Comment by mareksuscak** [comment]
```
yarn tsc --version
Version 5.0.4
✨  Done in 0.49s.
```

**Comment by TimMensch** [comment]
Post a simple reproduction. It worked when I made those changes. Others find the new code works. It's on you at this point to track down what's different about your environment.

It could be other packages, or Node version, or a bad node_modules install that just needs to be nuked and rebuilt.

**Comment by bryanjswift** [comment]
> @emrerdem1 @bryanjswift I was having the same problem, and I fixed it by bumping versions:
> 
> ```
>         "@chakra-ui/icons": "^2.0.18",
>         "@chakra-ui/react": "^2.5.5",
>         "@chakra-ui/system": "^2.5.5",
> ```
> 
> and
> 
> ```
>         "typescript": "^5.0.4",
> ```
> 
> With that set of updates, all of the instances of this warning that I was experiencing, plus all the examples given above (I just checked), have been fixed.

I have updated the minimal test case I provided in #7526 (viewable at https://gist.github.com/bryanjswift/3caee09992569aa385a15290842c3e92) to use `typescript` v5.0.4 and it still produces the same error. I'm glad you were able to resolve it by updating versions but something is definitely still going on that points to type errors.

**Comment by JakeGinnivan** [comment]
I found I had some duplicated chakra packages in my pnpm lockfile.

Setting `dedupe-peer-dependents=true` in my .npmrc

Then removing `"jsxImportSource": "@emotion/react",` from my tsconfig fixed it.

Running latest of everything now without the error.

**Comment by TimMensch** [comment]
I also find that removing `"jsxImportSource": "@emotion/react"` makes the bug go away in the minimal reproduction sample. Also commented on the related Open bug.

**Comment by SiarheiBobryk** [comment]
@TimMensch, the same works for me as well. Thanks, folks!

**Comment by QuentinDejean** [comment]
Same here @TimMensch  thank you SO MUCH for mentioning this!

**Comment by garrettparris** [comment]
fixed by downgrading typescript to ^4.9.5

**Comment by asankasira** [comment]
https://stackoverflow.com/a/77126751/3660710
