### ISSUE TITLE
Nextjs RSC error: It's currently unsupported to use "export *" in a client boundary

### ISSUE THREAD

**Issue by AdhamMoussa** [chakra-ui/chakra-ui#7878]
### Description

When I use Chakra component in a Nextjs RSC, I get an error: It's currently unsupported to use "export *" in a client boundary

![Screenshot (98)](https://github.com/chakra-ui/chakra-ui/assets/29588442/3115ea1e-a563-4117-b6c4-12128ac759b8)

### Link to Reproduction

https://codesandbox.io

### Steps to reproduce

1. use a Chakra component directly in a server component
2. see compilation error

### Chakra UI Version

2.8.0

### Browser

Google Chrome 114

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by dlibis** [comment]
doesn't work for me either, although latest release says it should. 
as a workaround you can create a new component, and write "use client" at the top of the file.
for example:

`
'use client';

import { Container, ContainerProps } from '@chakra-ui/react';
import { PropsWithChildren } from 'react';

export const ClientContainer: React.FC<PropsWithChildren & ContainerProps> = ({
  children,
  ...options
}) => {
  return <Container {...options}>{children}</Container>;
};
`

**Comment by dlibis** [comment]
@AdhamMoussa you can try the method seeing here https://youtu.be/fqfer6xMp2A?t=2733 
it works.

**Comment by maxloo2** [comment]
You can fix the problem by adding "use client" on top of each page that uses chakra too, but I have not tested if you actually need it on every page since I only encountered this on my small personal project.

**Comment by cupid-dev** [comment]
This workaround eliminates all of the benefits of using Server Components for static, non-interactive parts of the UI that use Chakra. Is there a better solution in the works?

**Comment by nappalm** [comment]
any solution? 😥

**Comment by dlibis** [comment]
@nappalm @cupid-dev you can create a file and do this:
'use client';
export {
  Card,
  HStack,
  Icon,
  Input,
  InputGroup,
  InputRightElement,
  SimpleGrid,
  Text,
  Box,
  CardHeader,
  CardBody,
  Heading,
  Flex,
  Container,
  Popover,
  PopoverContent,
  PopoverTrigger,
  PopoverArrow,
  Button,
  Checkbox,
  Grid,
  GridItem,
} from '@chakra-ui/react';

export { Link } from '@chakra-ui/next-js';

and import all modules from the file you just created

**Comment by filoscoder** [comment]
> @nappalm @cupid-dev you can create a file and do this:
> 
> ```
> 'use client';
> export {
>   Card,
>   HStack,
>   Icon,
>   Input,
>   InputGroup,
>   InputRightElement,
>   SimpleGrid,
>   Text,
>   Box,
>   CardHeader,
>   CardBody,
>   Heading,
>   Flex,
>   Container,
>   Popover,
>   PopoverContent,
>   PopoverTrigger,
>   PopoverArrow,
>   Button,
>   Checkbox,
>   Grid,
>   GridItem,
> } from '@chakra-ui/react';
> 
> export { Link } from '@chakra-ui/next-js';
> ```
> 
> and import all modules from the file you just created

Nice trick ;)

**Comment by cupid-dev** [comment]
> > @nappalm @cupid-dev you can create a file and do this:
> > ```
> > 'use client';
> > export {
> >   Card,
> >   HStack,
> >   Icon,
> >   Input,
> >   InputGroup,
> >   InputRightElement,
> >   SimpleGrid,
> >   Text,
> >   Box,
> >   CardHeader,
> >   CardBody,
> >   Heading,
> >   Flex,
> >   Container,
> >   Popover,
> >   PopoverContent,
> >   PopoverTrigger,
> >   PopoverArrow,
> >   Button,
> >   Checkbox,
> >   Grid,
> >   GridItem,
> > } from '@chakra-ui/react';
> > 
> > export { Link } from '@chakra-ui/next-js';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and import all modules from the file you just created
> 
> Nice trick ;)

But that makes them all client components and not server components, right? That’s what I’m trying to avoid, because it forfeits much of the benefit of Nextjs.

**Comment by filoscoder** [comment]
> > > @nappalm @cupid-dev you can create a file and do this:
> > > ```
> > > 'use client';
> > > export {
> > >   Card,
> > >   HStack,
> > >   Icon,
> > >   Input,
> > >   InputGroup,
> > >   InputRightElement,
> > >   SimpleGrid,
> > >   Text,
> > >   Box,
> > >   CardHeader,
> > >   CardBody,
> > >   Heading,
> > >   Flex,
> > >   Container,
> > >   Popover,
> > >   PopoverContent,
> > >   PopoverTrigger,
> > >   PopoverArrow,
> > >   Button,
> > >   Checkbox,
> > >   Grid,
> > >   GridItem,
> > > } from '@chakra-ui/react';
> > > 
> > > export { Link } from '@chakra-ui/next-js';
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and import all modules from the file you just created
> > 
> > 
> > Nice trick ;)
> 
> But that makes them all client components and not server components, right? That’s what I’m trying to avoid, because it forfeits much of the benefit of Nextjs.

I came here because I'm using Chakra UI with Next.js 13. By default, next uses server components and Chakra only client components. That's why you need `providers` to make it work.  (See [docs](https://chakra-ui.com/getting-started/nextjs-guide#app-directory-setup))

**Comment by Tbhesswebber** [comment]
This doesn't address one of the big issues, which is importing server-side utilities and leveraging them.  I managed to get around this for most things, but importing the `cookieStorageManager` is causing this to happen and, as far as I know, there isn't a possible workaround.

**Comment by Digitl-Alchemyst** [comment]
Would using one of these methods above just make the component you are reexporting charka too a client component essential being the same thing as marking everything chakra uses with client side flag?

**Comment by MattEspoz** [comment]
Any updated solutions :(

**Comment by imgopaal** [comment]
> > > @nappalm @cupid-dev you can create a file and do this:
> > > ```
> > > 'use client';
> > > export {
> > >   Card,
> > >   HStack,
> > >   Icon,
> > >   Input,
> > >   InputGroup,
> > >   InputRightElement,
> > >   SimpleGrid,
> > >   Text,
> > >   Box,
> > >   CardHeader,
> > >   CardBody,
> > >   Heading,
> > >   Flex,
> > >   Container,
> > >   Popover,
> > >   PopoverContent,
> > >   PopoverTrigger,
> > >   PopoverArrow,
> > >   Button,
> > >   Checkbox,
> > >   Grid,
> > >   GridItem,
> > > } from '@chakra-ui/react';
> > > 
> > > export { Link } from '@chakra-ui/next-js';
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and import all modules from the file you just created
> > 
> > 
> > Nice trick ;)
> 
> But that makes them all client components and not server components, right? That’s what I’m trying to avoid, because it forfeits much of the benefit of Nextjs.

All the components are already on client. As you will got inside node modules. you will see the there is already "use client" written on all of them

**Comment by segunadebayo** [comment]
This is now fixed in the latest version of Chakra

**Comment by annetters** [comment]
I am still encountering this error as of 10/11/2023. I am on the latest versions. 

    "@chakra-ui/icons": "^2.1.1",
    "@chakra-ui/next-js": "^2.1.5",
    "@chakra-ui/react": "^2.8.1",

I cannot export a module unless I put 'use client' at the top of my file.

![image](https://github.com/chakra-ui/chakra-ui/assets/751308/1649b936-e8f7-4b9d-b862-1e57406ae6d8)

**Comment by ceconcarlsen** [comment]
any updates?

**Comment by ceconcarlsen** [comment]
> I am still encountering this error as of 10/11/2023. I am on the latest versions. (cc @segunadebayo - Thank you, either way.)
> 
> ```
> "@chakra-ui/icons": "^2.1.1",
> "@chakra-ui/next-js": "^2.1.5",
> "@chakra-ui/react": "^2.8.1",
> ```
> 
> I cannot export a module unless I put 'use client' at the top of my file. Is there a way to fix this error without having to use 'use client'?
> 
> ![image](https://user-images.githubusercontent.com/751308/274357073-1649b936-e8f7-4b9d-b862-1e57406ae6d8.png)
> 
> To reproduce: I created and exported a TSX module with [this code snippet from Chakra-Templates.dev](url), except I have removed the 'use client' from the top.

after i updated to the last version of Chakra as [segunadebayo](https://github.com/segunadebayo) commented and CLEARED cache, the issue was gone

**Comment by riseshia** [comment]
Same here with `@chakra-ui/icons/dist/index.mjs`. with 2.11 🤔 

<img width="761" alt="error" src="https://github.com/chakra-ui/chakra-ui/assets/7338443/1c8d27c0-6502-4925-bfb7-591f69b7c421">

**Comment by Andrei-Ist** [comment]
Is there clarity on this topic? I'm trying to remove the "use client" but I'm getting the same error as above, I have the same packages installed. Doesn't seem to be a cache issue, as I'm using this in incognito. 
```
"@chakra-ui/icons": "^2.1.1",
"@chakra-ui/next-js": "^2.1.5",
"@chakra-ui/react": "^2.8.1",
```

Are there the usage of the CacheProvider and ChakraProvider different from the guide on Chakra Website to be able to remove the "use client" directive?

**Comment by jocruz** [comment]
Has there been any update on this? I just ran into the same issue and putting 'use client' on top seems to fix the issue however after reading much documentation it doesn't seem like that is the optimal solution

**Comment by diegosurita** [comment]
I'm also still having this problem! Is there any effort being done to fix this?

**Comment by GregerGu** [comment]
I am also experiencing this issue. Any update here?

**Comment by BitHighlander** [comment]
I dont know why this issue is closed, its still an issue

**Comment by JoaoVitorLima242** [comment]
It is still happening and I don't want to lose the server side of my components. Does someone know how to handle it or open the issue again?

**Comment by webstercharly** [comment]
same issue 
```
"dependencies": {
    "@chakra-ui/icons": "^2.1.1",
    "@chakra-ui/react": "^2.8.2",
    "next": "14.1.3",
    ...
  },
  ```

**Comment by pablojsx** [comment]
same problem and I was trying to fix another issue, this happened when i deleted th elock and node_modules files

**Comment by daphnesaj** [comment]
> same problem and I was trying to fix another issue, this happened when i deleted th elock and node_modules files and reinstalled everything
> 
> ![image](https://private-user-images.githubusercontent.com/40902487/323023369-c6b672e0-16c6-4d27-a0ea-9403dd14d844.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNDU4NTksIm5iZiI6MTcxMzM0NTU1OSwicGF0aCI6Ii80MDkwMjQ4Ny8zMjMwMjMzNjktYzZiNjcyZTAtMTZjNi00ZDI3LWEwZWEtOTQwM2RkMTRkODQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA5MTkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YzU2N2Y0NjY5ZmNkZGE2NjY5NTU4NGI2NGZhODIzNjRmNjM1NTU4YmM0ZmE1NTg3N2U5N2RkZTU3OWI3NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2pma_PVUjWyahUfaaCCWgB6-Ueibe9-9GEXVh5BxTVY)

**Comment by pablojsx** [comment]
solved it, you should add at the top "use client" where you use nextui, if you have a server component just create a client component and then import it into the server component

**Comment by mklsk** [comment]
Still an issue

**Comment by Sadman95** [comment]
still having issue
![image](https://github.com/user-attachments/assets/c0560424-2106-4b30-9e1b-3bbf81fa6fbf)

**Comment by vagra** [comment]
![图片](https://github.com/user-attachments/assets/c71db841-5b7d-463e-acad-648ffa67c62c)
```
import { CheckIcon } from '@chakra-ui/icons';

...

<ListIcon as={CheckIcon} />
```

**Comment by arealesramirez** [comment]
I'm also experiencing the same when attempting to use an icon
```
import { WarningIcon } from "@chakra-ui/icons";
import { Box, Heading, List, ListIcon, ListItem, Text } from "@chakra-ui/react";

... component rendering below
          <ListItem>
            <ListIcon as={WarningIcon} color="red.500" />
            Reading assignment submissions
          </ListItem>
```

```
    "@chakra-ui/icons": "^2.1.1",
    "@chakra-ui/next-js": "^2.2.0",
    "@chakra-ui/react": "^2.8.2",
```
![Screenshot 2024-09-13 at 3 14 57 PM](https://github.com/user-attachments/assets/1ee8eb09-1ecf-4a0b-807e-ea241f4ed77d)

**Comment by IvanCCO** [comment]
> solved it, you should add at the top "use client" where you use nextui, if you have a server component just create a client component and then import it into the server component

This works for me!
