### ISSUE TITLE
[Regression] Slider thumb offset issue

### ISSUE THREAD

**Issue by andrey-mitko** [chakra-ui/chakra-ui#8945]
### Description

We have recently attempted to update `@chakra-ui/react` from `v2.8.2` to `v2.10.3` but noticed a bug with the `Slider` component. 

It looks like the `SliderThumb` component gets rendered with a slight offset compared to the actual value. The following appears to be the case for both keyboard and mouse interactions. Interestingly, due to the following issue, the `SliderThumb` component could be moved beyond the `SliderTrack`.

### Link to Reproduction

https://v2.chakra-ui.com/docs/components/slider/usage

### Steps to reproduce

1. Click in the centre of the slider thumb
2. Notice how the slider thumb jumps slightly to the right
3. Move the slider to the end of the available track
4. Notice how the slider thumb moves beyond the available track

### Chakra UI Version

2.10.3

### Browser

Google Chrome 129.0.6668.101

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

One of the most recent changes in the relevant files appears to be https://github.com/chakra-ui/chakra-ui/commit/5d7743ec0cf234ff22fbb675a8f5846c8cd7ae9e

<video src="https://github.com/user-attachments/assets/9c3bd690-415f-4aa1-9606-12fcab515d27"></video>

<img width="904" alt="Screenshot 2024-10-17 at 10 29 31" src="https://github.com/user-attachments/assets/4dd2bd07-10fb-4fb1-baec-3f7f73915376">

**Comment by Mackhack0705** [comment]
Hi @andrey-mitko, I want to work on this issue. I have set up the project locally and I want to know if there is a way or command to see what's happening with the slider locally. In other words, is there any way to run it locally so I can see the slider and observe the changes I make?

**Comment by andrey-mitko** [comment]
Hi @Mackhack0705, in order to see the changes locally, please run the `pnpm storybook` command. 
Once the storybook is running, you should be able to navigate to `http://localhost:6006` and see the changes under the `Components > Forms > Slider` stories.

You can find more information about contributing to Chakra UI here:
https://v2.chakra-ui.com/getting-started/contributing

**Comment by segunadebayo** [comment]
Correct @andrey-mitko 

I pushed a fix for this. Will publish a patch shortly.

**Comment by andrey-mitko** [comment]
@segunadebayo, thank you for looking into this issue. Unfortunately, it still appears to be a problem for sliders with custom slider thumb sizes. 

You can find an example of such a slider under the `Customizing the Slider` section on the V2 Chakra UI docs:
https://v2.chakra-ui.com/docs/components/slider/usage#customizing-the-slider
